# -*- coding: utf-8 -*-
"""English strings + bilingual rule metadata (zh/en)."""

EN = {
    # Common
    "common.selected": "Selected", "common.freeable": "recoverable", "common.viewall": "View all",
    "common.loading": "Loading…", "common.scanning": "Scanning…", "common.n.items": "{0} items",
    "common.approx": "~", "btn.cancel": "Cancel", "btn.exit": "Exit", "btn.refresh": "Refresh",
    "btn.stopscan": "Stop scan", "btn.rescan": "Scan again", "btn.restore": "Restore", "btn.deleteperm": "Delete permanently",
    "btn.uninstall": "Uninstall", "btn.recycle": "Move to Recycle Bin", "btn.remove": "Remove", "btn.analyze.start": "Analyze",
    "btn.scan.now": "Scan now", "btn.more": "More tools", "btn.clean.selected": "Clean selected",
    "btn.clean.start": "Start cleaning", "btn.done.home": "Back to Home", "btn.done.quarantine": "Open quarantine",
    "btn.emptybin": "Empty Recycle Bin", "btn.openbin": "Open Recycle Bin", "btn.scangroup": "Scan group",
    "btn.cleansel": "Clean selected", "btn.dupscan": "Start scan", "btn.dup.rescan": "Scan again",
    "btn.dupkeepnew": "Keep newest, select rest", "btn.dupclean": "Move selected to Recycle Bin",
    "btn.clearhistory": "Clear history", "btn.clearlocal": "Clear local history", "btn.purge": "Empty quarantine",
    "btn.shredfile": "Shred files…", "btn.shreddir": "Shred folder…", "btn.shred": "Shred permanently",
    "tip.min": "Minimize", "tip.max": "Maximize", "tip.close": "Close",
    "nav.home": "Home", "nav.scan": "Smart Scan", "nav.clean": "Clean Space", "nav.space": "Space Analysis",
    "nav.startup": "Startup", "nav.apps": "Apps", "nav.toolbox": "Toolbox", "nav.settings": "Settings",
    "risk.safe": "Safe", "risk.low": "Low risk", "risk.confirm": "Review", "risk.high": "High risk",
    "cat.system": "System", "cat.apps": "Apps", "cat.images": "Images", "cat.videos": "Videos",
    "cat.audio": "Audio", "cat.documents": "Documents", "cat.archives": "Archives", "cat.other": "Other",
    "time.now": "Just now", "time.minago": "{0} min ago", "time.today": "Today {0}", "time.yesterday": "Yesterday {0}",
    # Home
    "home.slogan": "Regular scans keep your PC at its best",
    "home.status.good": "Your PC is in good shape", "home.status.suggest": "A cleanup is recommended", "home.status.tight": "Disk space is low",
    "home.status.suggest.detail": "{0} of cleanable junk and {1} high-impact startup items found",
    "home.status.tight.detail": "Less than 10% free on the system drive — clean up now",
    "home.status.lastscan": "Last scan: {0}", "home.noscan": "Not scanned yet", "home.noscan.detail": "Not scanned yet — click “Scan now” to begin",
    "home.card.junk": "Cleanable junk", "home.card.junk.note": "Scan to see reclaimable space", "home.card.junk.lastscan": "Last scan {0}",
    "home.card.startup": "Startup items", "home.card.startup.note": "startup items run at boot", "home.card.startup.note.high": "high-impact items may slow boot",
    "home.card.large": "Large files", "home.card.large.note": "Analyze to find", "home.card.large.analyzed": "Analyzed",
    "home.card.large.analyzed.note": "Click to browse large files", "home.card.large.pending": "Pending",
    "home.card.apps": "Installed apps", "home.card.apps.note": "Click to manage installed apps",
    "home.disk.title": "Disk space (C:)", "home.disk.title.disk": "Disk space ({0})", "home.disk.total": "Total —",
    "home.disk.used": "Used —", "home.disk.free": "Free —", "home.disk.total.f": "Total {0}",
    "home.disk.used.f": "Used {0} ({1:F1}%)", "home.disk.free.f": "Free {0} ({1:F1}%)", "home.disk.more": "Where did my space go →",
    "home.space.title": "Space Analysis", "home.space.empty": "This drive hasn't been analyzed yet",
    "home.activity.title": "Recent activity", "home.activity.empty": "No activity yet — run a scan and cleanup",
    "home.suggest.title": "Smart suggestions", "home.suggest.empty": "All good — nothing needs attention",
    "home.suggest.note.safe": "Safe to clean, no impact on your system", "home.suggest.clean": "Clean now", "home.suggest.optimize": "Optimize",
    "home.suggest.startup.title": "Startup suggestion", "home.suggest.startup.note": "{0} high-impact startup items found — consider optimizing",
    "home.hero.note": "A cleaner PC,\na smoother run!",
    # Smart scan
    "scan.start": "Start scan", "scan.cover": "One scan covers: system junk · browser caches · app caches · Recycle Bin",
    "scan.privacy": "Everything runs locally; only safe items are pre-selected, and high-risk items are never auto-selected.",
    "scan.preparing": "Preparing…", "scan.found": "Found —", "scan.done": "Scan complete",
    "scan.reselectall": "Select safe items",
    "scan.group.safe": "Safe to clean", "scan.group.safe.note": "Temporary data created by the system and apps — safe to remove",
    "scan.group.cache": "Browser & app caches", "scan.group.cache.note": "Cache data; apps re-download when needed",
    "scan.group.check": "Needs review", "scan.group.check.note": "Confirm these are no longer needed before cleaning",
    "result.title.found": "Scan complete — {0} recoverable", "result.title.clean": "Scan complete — all clean!",
    "result.sub": "{0} · {1} categories scanned",
    "row.files": "{0} files", "row.restore": "restorable via quarantine", "row.direct": "deleted directly",
    "row.running": "{0} related processes running", "row.impact.tip": "Impact: {0}",
    # Cleaning
    "clean.title": "Cleaning…", "clean.freed": "Freed —",
    "done.title": "Cleanup complete", "done.cancelled": "Cleanup interrupted", "done.partial": "Cleanup complete (some skipped)",
    "done.freed.total": "{0} freed in total", "done.note.quarantine": "Quarantined files are kept {0} days and can be restored from the Toolbox.",
    "done.note.skip": "Skipped files are in use by other programs; close them and clean again later.",
    "done.stat.ok": "Cleaned", "done.stat.quar": "Quarantined", "done.stat.skip": "Skipped (in use)", "done.stat.fail": "Failed",
    # Clean space
    "clean.tab.system": "System junk", "clean.tab.app": "App caches", "clean.tab.browser": "Browsers",
    "clean.tab.privacy": "Privacy traces", "clean.tab.recycle": "Recycle Bin",
    "clean.tabnote.0": "Temp files, logs and crash reports from the system and apps — only safe items pre-selected",
    "clean.tabnote.1": "Caches and logs of chat & office apps — your chats and documents are never touched",
    "clean.tabnote.2": "Browser caches that speed up browsing — logins, passwords and history unaffected",
    "clean.tabnote.3": "Personal records — all unchecked by default; review each impact carefully",
    "clean.tabnote.4": "Confirm the Recycle Bin holds nothing you need before emptying",
    "clean.privacy.banner": "Privacy items are unchecked by default. Read each impact before selecting: clearing cookies signs you out; clearing history cannot be undone.",
    "clean.privacy.warn": "Privacy items cannot be restored after cleaning. Make sure you understand the impact.",
    "clean.recycle.desc": "Emptying the Recycle Bin permanently deletes its files. You can also open it to check first.",
    "clean.empty.before": "Click “Scan group” below to check this category", "clean.empty.clean": "This category is clean — nothing to remove",
    "clean.empty.group": "Click “Scan group” below to check this category",
    "recycle.info": "{0} items, occupying {1}", "recycle.empty": "The Recycle Bin is empty",
    "recycle.confirm.title": "Empty Recycle Bin?", "recycle.confirm.msg": "{0} files ({1}) will be permanently deleted. This cannot be undone.",
    "toast.cleandone": "Cleaned — {0} freed", "toast.skipped": " ({0} skipped)", "toast.binemptied": "Recycle Bin emptied",
    "toast.failed": "Operation failed",
    "dlg.clean.selected.title": "Clean the selected items?", "dlg.clean.amount": "About to clean {0} of data.",
    "dlg.clean.nrules": "About to clean {0} categories, {1} in total.", "dlg.clean.confirmitems": "Items that need review:",
    "dlg.clean.quarantinehint": "Restorable files will be moved to quarantine.",
    "dlg.quickclean.title": "Clean {0}?", "dlg.quickclean.msg": "About {0} will be freed.\nRestorable files go to quarantine.",
    # Space analysis
    "space.tab.overview": "Overview", "space.tab.large": "Large files", "space.tree.title": "Folder usage ranking",
    "space.tree.hint": "Click to expand; system links and inaccessible folders are skipped",
    "space.empty": "This drive hasn't been analyzed yet. Click “Analyze” above (you can cancel anytime)",
    "space.scanning": "Analyzing disk…", "space.cancelled": "Analysis cancelled", "space.failed": "Analysis failed: ",
    "space.done": "Analysis finished in {0:F0} s", "space.rendererror": "Failed to render analysis results — see log",
    "space.scanned": "{0:N0} files scanned", "space.total": "total {0}",
    "space.used.f": "Used {0} / {1} ({2:F1}%), free {3}", "space.used.f2": "Used {0} / {1}, free {2}",
    "space.analyzed.f": "Analyzed {0} · {1:N0} files · {2:F0} s", "space.lastanalysis": "Last analysis: {0}",
    "space.notanalyzed": "This drive hasn't been analyzed yet", "space.large.filter": "Size filter",
    "space.large.none": "No files larger than {0:F0} MB found", "space.modified": "Modified", "space.file": "FILE",
    "space.recycle.title": "Move to Recycle Bin?", "space.recycle.msg": "{0} ({1}) will be moved to the Recycle Bin. You can restore it anytime.",
    "toast.whitelisted": "Added to whitelist — scans and cleanups will skip this file",
    "toast.largecleaned": "Cleaned large file {0}", "toast.recycled": "Moved to Recycle Bin — {0} freed",
    "toast.recyclefailed": "Failed to move to Recycle Bin; the file may be in use",
    # Startup
    "startup.desc": "Disabled apps can still be opened manually; every change keeps its original state and can be reverted.",
    "startup.col.toggle": "State", "startup.col.impact": "Impact", "startup.col.source": "Source", "startup.col.suggest": "Advice",
    "startup.loading": "Loading startup items…", "startup.empty": "No matching startup items", "startup.systemchip": "System component",
    "startup.src.reghkcu": "Registry (current user)", "startup.src.reghklm": "Registry (machine)",
    "startup.src.folderuser": "Startup folder (user)", "startup.src.foldercommon": "Startup folder (all users)",
    "startup.src.task": "Scheduled task", "startup.impact.high": "High", "startup.impact.med": "Medium",
    "startup.impact.low": "Low", "startup.impact.unknown": "Unrated",
    "startup.suggest.off": "Consider disabling", "startup.suggest.system": "System component", "startup.suggest.keep": "Keep",
    "startup.enabled": "Enabled", "startup.disabled": "Disabled", "startup.toggled": "{0} startup item “{1}”",
    # Apps
    "apps.desc": "Uninstalling launches the app's own uninstaller; afterwards confirmed leftovers can be cleaned (into quarantine, restorable).",
    "apps.sort.name": "By name", "apps.sort.size": "By size", "apps.sort.date": "By install date",
    "apps.col.name": "App", "apps.col.publisher": "Publisher", "apps.col.size": "Size", "apps.col.date": "Installed",
    "apps.loading": "Loading installed apps…", "apps.empty": "No matching apps", "apps.store": "Microsoft Store app",
    "apps.unknown": "Unknown", "apps.uninstall.title": "Uninstall {0}?", "apps.uninstall.start": "Start uninstall",
    "apps.uninstall.msg": "App size: {0}\n\nThe app's own uninstaller will launch — follow its wizard to finish.",
    "apps.waiting": "Waiting for “{0}” to uninstall…\nContinues automatically once finished",
    "apps.notdetected": "Uninstall not detected — it may have been cancelled",
    "apps.uninstalled.toast": "“{0}” has been uninstalled", "apps.uninstalled.log": "Uninstalled app “{0}”",
    "apps.uninstall.failed": "Failed to launch uninstaller: ",
    # Leftovers
    "leftover.title": "Possible leftovers found", "leftover.title.f": "Leftovers of “{0}”",
    "leftover.desc": "Data folders and setting keys that belong to this app. Selected items go to quarantine (restorable).",
    "leftover.skip": "Skip, done", "leftover.clean": "Clean selected", "leftover.reg": "Settings registry key (backed up, then removed)",
    "leftover.datadir": "Data folder", "leftover.installdir": "Install folder",
    # Toolbox
    "tool.desc": "Shredded files bypass the Recycle Bin; quarantined files are restorable; duplicates are found by content hashing.",
    "tool.quarantine.title": "Cleanup quarantine", "tool.quar.empty": "Quarantine is empty",
    "tool.quar.summary": "{0} items, {1}; auto-deleted after {2} days",
    "tool.quar.daysleft": "{0} days left", "tool.purge.title": "Empty quarantine?",
    "tool.purge.msg": "{0} quarantined items will be permanently deleted. This cannot be undone.",
    "tool.shred.title": "File shredder", "tool.shred.desc": "Permanently deletes files from the file system without the Recycle Bin. Note: on SSDs immediate physical overwriting cannot be guaranteed. Irreversible — choose files carefully.",
    "tool.shred.confirm.title": "Shred this item?", "tool.shred.confirm.msg": "{0}\n\n{1} will be overwritten and permanently deleted — it bypasses the Recycle Bin and cannot be recovered by software.\n\nThis cannot be undone!",
    "tool.shred.log": "Shredded {0} “{1}”", "tool.folder": "folder", "tool.file": "file",
    "tool.dup.title": "Duplicate files", "tool.dup.desc": "Duplicates are confirmed by content hashing (never by file name). Default scope: Pictures, Videos and Downloads.",
    "tool.dup.none": "No duplicate files found", "tool.dup.summary": "{0} duplicate groups, {1} recoverable",
    "tool.dup.progress": "{0:N0} files scanned…", "tool.dup.more": "… {0} more groups not shown",
    "tool.dup.group": "{0} identical files · {1} each · {2} recoverable", "tool.dup.tip": "Checked = delete this copy",
    "tool.dup.clean.title": "Delete selected copies?", "tool.dup.clean.msg": "{0} files, {1}, will be moved to the Recycle Bin (restorable).",
    "tool.history.title": "Clean history", "tool.win.title": "Windows quick tools", "tool.win.desc": "Direct shortcuts to built-in system tools — safe and reliable",
    "tool.win.taskmgr": "Task Manager", "tool.win.taskmgr.d": "Processes and performance",
    "tool.win.storage": "Storage settings", "tool.win.storage.d": "Manage storage",
    "tool.win.diskmgmt": "Disk Management", "tool.win.diskmgmt.d": "Manage partitions and disks",
    "tool.win.devmgmt": "Device Manager", "tool.win.devmgmt.d": "Manage hardware and drivers",
    "tool.win.control": "Control Panel", "tool.win.control.d": "Classic system settings",
    "tool.win.msinfo": "System Information", "tool.win.msinfo.d": "View system configuration",
    "tool.win.update": "Windows Update", "tool.win.update.d": "Check for system updates",
    "tool.win.restore": "System Restore", "tool.win.restore.d": "Create or use restore points",
    # History
    "history.empty": "No activity yet", "history.clear.title": "Clear history?", "history.clear.msg": "All cleaning and operation records will be deleted.",
    "history.type.clean": "Clean", "history.type.autoclean": "Auto-clean", "history.type.restore": "Restore",
    "history.type.uninstall": "Uninstall", "history.type.startup": "Startup", "history.type.quarantine": "Quarantine",
    "history.type.shred": "Shred", "history.type.other": "Other",
    # Settings
    "settings.title": "Settings", "settings.sec.general": "General", "settings.sec.exclude": "Exclusions & whitelist",
    "settings.sec.notify": "Notifications", "settings.sec.advanced": "Advanced", "settings.sec.privacy": "Privacy", "settings.sec.about": "About",
    "settings.exc.desc": "These folders and files are skipped by every scan and cleanup.", "settings.exc.empty": "No exclusions or whitelist entries",
    "settings.whitelist": "Whitelist", "settings.excluded": "Excluded",
    "settings.btn.addexclude": "Add excluded folder", "settings.btn.addwhitelist": "Add whitelisted file/folder",
    "settings.pick.whitelist": "Choose a file to whitelist", "settings.pick.exclude": "Choose a folder to exclude from scans",
    "settings.days": "days", "settings.threads": "threads",
    "settings.theme.light": "Light", "settings.theme.dark": "Dark", "settings.theme.system": "Follow system",
    "settings.freq.daily": "Daily", "settings.freq.weekly": "Weekly", "settings.freq.monthly": "Monthly",
    "settings.lang.auto": "Follow system language",
    "settings.row.language": "Interface language", "settings.row.language.d": "Applied immediately",
    "settings.row.autostart": "Run at Windows startup", "settings.row.autostart.d": "Waits silently in the tray after boot; does nothing on its own",
    "settings.row.mintotray": "Minimize to tray", "settings.row.mintotray.d": "The minimize button hides to the tray",
    "settings.row.closetotray": "Close button minimizes to tray", "settings.row.closetotray.d": "The close button asks and minimizes instead of exiting",
    "settings.row.theme": "Theme",
    "settings.row.quarantine": "Quarantine after cleaning", "settings.row.quarantine.d": "Non-cache files go to quarantine first, restorable (recommended)",
    "settings.row.quarantine.days": "Quarantine retention", "settings.row.quarantine.days.d": "Auto-deleted permanently after expiry",
    "settings.row.autoclean": "Automatic cleaning", "settings.row.autoclean.d": "Cleans safe items such as temp files and caches on schedule",
    "settings.row.autoclean.freq": "Auto-clean frequency", "settings.row.autoclean.freq.d": "Runs in the background while the app is running",
    "settings.row.notifydisk": "Low disk space alert", "settings.row.notifydisk.d": "Alerts when the system drive drops below 10% (rare, non-intrusive)",
    "settings.row.notifyauto": "Auto-clean results", "settings.row.notifyweekly": "Weekly space report",
    "settings.row.notifynews": "Product news", "settings.row.notifynews.d": "Feature and event announcements, off by default",
    "settings.row.threads": "Scan threads", "settings.row.threads.d": "More threads = faster; use fewer on HDDs",
    "settings.row.hidden": "Scan hidden files", "settings.row.junction": "Follow directory links (Junctions)",
    "settings.row.junction.d": "Following links may double-count data; off by default",
    "settings.row.stats": "Anonymous usage stats", "settings.row.stats.d": "Would only report feature counts and error codes — this build never uploads anything",
    "settings.row.crash": "Crash reports",
    "settings.privacy.desc": "All scan data stays on this device. This app never collects or uploads file names, paths or contents.",
    "settings.about.slogan": "Clean with clarity, optimize with confidence.", "settings.about.support": "Support & feedback",
    "settings.about.site": "Website", "settings.about.email": "Email", "settings.about.repo": "Source code",
    "settings.about.wechat": "Scan or search “AI虚拟助理” in WeChat for tips and updates.",
    # Wizard
    "wizard.welcome": "Welcome to CleanMaster",
    "wizard.slogan": "Clean with clarity, optimize with confidence.\nWe only do explainable, previewable, restorable cleaning — no fake boosts.",
    "wizard.privacy.title": "Our privacy promise",
    "wizard.privacy.items": "· All scan results, file names and paths stay on this PC.\n· No telemetry is enabled by default; no file contents are ever uploaded.\n· Key cleanups go to quarantine — restorable for 7~30 days.\n· Always previewed before deletion — never silently removed.",
    "wizard.auto.title": "Enable automatic cleaning?", "wizard.auto.desc": "Only cleans safe items such as temp files and app caches, once a week.",
    "wizard.auto.yes": "Enable auto-clean", "wizard.auto.no": "Not now", "wizard.next": "Get started", "wizard.next2": "Next",
    # Tray
    "tray.open": "Open CleanMaster", "tray.quickscan": "Quick scan", "tray.exit": "Exit",
    "tray.autoclean": "Auto-clean: ", "tray.on": "On", "tray.off": "Off",
    # Dialogs/toasts
    "dlg.exit.title": "Exit CleanMaster?", "dlg.exit.msg": "Auto-cleaning and disk space monitoring stop when you exit.",
    "toast.traymin": "Minimized to tray — right-click the tray icon to exit",
    "toast.scanstopped": "Scan stopped", "toast.scanfailed": "Scan failed: ", "toast.noselect": "Select items to clean first",
    "toast.cleancancelled": "Cleaning cancelled", "toast.cleanfailed": "Cleaning failed: ", "toast.nothing": "Nothing found to clean",
    "toast.cleaned": "Cleaned — {0} freed", "toast.readfailed": "Failed to load: ", "toast.langapplied": "Language changed",
}
