# -*- coding: utf-8 -*-
"""日本語・한국어（UI 級；規則の詳細文は en-US へフォールバック）。"""

JA = {
    "common.selected": "選択中", "common.freeable": "解放可能", "common.viewall": "すべて表示",
    "common.loading": "読み込み中…", "common.scanning": "スキャン中…", "common.n.items": "{0} 件",
    "common.approx": "約 ", "btn.cancel": "キャンセル", "btn.exit": "終了", "btn.refresh": "更新",
    "btn.stopscan": "スキャン停止", "btn.rescan": "再スキャン", "btn.restore": "復元", "btn.deleteperm": "完全に削除",
    "btn.uninstall": "アンインストール", "btn.recycle": "ごみ箱へ移動", "btn.remove": "削除", "btn.analyze.start": "解析開始",
    "btn.scan.now": "今すぐスキャン", "btn.more": "その他の機能", "btn.clean.selected": "選択項目をクリーンアップ",
    "btn.clean.start": "クリーンアップ開始", "btn.done.home": "ホームへ戻る", "btn.done.quarantine": "隔離区を開く",
    "btn.emptybin": "ごみ箱を空にする", "btn.openbin": "ごみ箱を開く", "btn.scangroup": "このグループをスキャン",
    "btn.cleansel": "選択項目をクリーンアップ", "btn.dupscan": "スキャン開始", "btn.dup.rescan": "再スキャン",
    "btn.dupkeepnew": "最新を残して選択", "btn.dupclean": "選択項目をごみ箱へ",
    "btn.clearhistory": "履歴を消去", "btn.clearlocal": "ローカル履歴を消去", "btn.purge": "隔離区を空にする",
    "btn.shredfile": "ファイルをシュレッド", "btn.shreddir": "フォルダをシュレッド", "btn.shred": "完全にシュレッド",
    "tip.min": "最小化", "tip.max": "最大化", "tip.close": "閉じる",
    "nav.home": "ホーム", "nav.scan": "スマートスキャン", "nav.clean": "クリーンアップ", "nav.space": "ディスク解析",
    "nav.startup": "スタートアップ", "nav.apps": "アプリ管理", "nav.toolbox": "ツールボックス", "nav.settings": "設定",
    "risk.safe": "安全", "risk.low": "低リスク", "risk.confirm": "要確認", "risk.high": "高リスク",
    "cat.system": "システム", "cat.apps": "アプリ", "cat.images": "画像", "cat.videos": "動画",
    "cat.audio": "音楽", "cat.documents": "ドキュメント", "cat.archives": "アーカイブ", "cat.other": "その他",
    "time.now": "たった今", "time.minago": "{0} 分前", "time.today": "今日 {0}", "time.yesterday": "昨日 {0}",
    "home.slogan": "定期的なスキャンで PC を最高の状態に保ちましょう",
    "home.status.good": "デバイスは良好です", "home.status.suggest": "クリーンアップをおすすめします", "home.status.tight": "ディスク空き容量が少ないです",
    "home.status.suggest.detail": "クリーンアップ可能 {0} と高影響スタートアップ {1} 件が見つかりました",
    "home.status.tight.detail": "システムドライブの空きが 10% 未満です。今すぐ整理しましょう",
    "home.status.lastscan": "前回のスキャン：{0}", "home.noscan": "まだスキャンしていません", "home.noscan.detail": "「今すぐスキャン」をクリックして開始しましょう",
    "home.card.junk": "クリーンアップ可能なゴミ", "home.card.junk.note": "スキャンして解放容量を確認", "home.card.junk.lastscan": "前回スキャン {0}",
    "home.card.startup": "スタートアップ", "home.card.startup.note": "件が起動時に実行中", "home.card.startup.note.high": "高影響スタートアップが起動を遅くする可能性",
    "home.card.large": "大容量ファイル", "home.card.large.note": "解析して検索", "home.card.large.analyzed": "解析済み",
    "home.card.large.analyzed.note": "クリックして詳細を表示", "home.card.large.pending": "未解析",
    "home.card.apps": "インストール済みアプリ", "home.card.apps.note": "クリックして管理",
    "home.disk.title": "ディスク空き容量 (C:)", "home.disk.title.disk": "ディスク容量 ({0})", "home.disk.total": "合計 —",
    "home.disk.used": "使用中 —", "home.disk.free": "空き —", "home.disk.total.f": "合計 {0}",
    "home.disk.used.f": "使用中 {0} ({1:F1}%)", "home.disk.free.f": "空き {0} ({1:F1}%)", "home.disk.more": "空き容量の内訳を見る →",
    "home.space.title": "ディスク解析", "home.space.empty": "このドライブはまだ解析されていません",
    "home.activity.title": "最近のアクティビティ", "home.activity.empty": "履歴はまだありません。スキャンしてみましょう",
    "home.suggest.title": "スマート候補", "home.suggest.empty": "問題ありません。対処が必要な項目はありません",
    "home.suggest.note.safe": "安全にクリーンアップでき、システムに影響しません", "home.suggest.clean": "今すぐ清理", "home.suggest.optimize": "最適化",
    "home.suggest.startup.title": "スタートアップの候補", "home.suggest.startup.note": "高影響スタートアップ {0} 件。最適化をおすすめします",
    "home.hero.note": "PC をきれいに、\n動きをスムーズに！",
    "scan.start": "スキャン開始", "scan.cover": "ワンステップで：システムゴミ · ブラウザキャッシュ · アプリキャッシュ · ごみ箱",
    "scan.privacy": "すべてローカルで実行。安全な項目のみ既定で選択され、高リスク項目が自動選択されることはありません。",
    "scan.preparing": "準備中…", "scan.found": "検出 —", "scan.done": "スキャン完了", "scan.reselectall": "安全項目を選択",
    "scan.group.safe": "安全に清理可能", "scan.group.safe.note": "システムとアプリが生成した一時データ。削除しても安全です",
    "scan.group.cache": "ブラウザ・アプリキャッシュ", "scan.group.cache.note": "必要時にアプリが再ダウンロードします",
    "scan.group.check": "要確認", "scan.group.check.note": "クリーンアップ前に内容を確認してください",
    "result.title.found": "スキャン完了。{0} 解放可能", "result.title.clean": "スキャン完了。とてもきれいです！",
    "result.sub": "{0} · {1} カテゴリをスキャン",
    "row.files": "{0} ファイル", "row.restore": "隔離区から復元可", "row.direct": "直接削除",
    "row.running": "関連プロセス {0} 個が実行中", "row.impact.tip": "クリーンアップの影響：{0}",
    "clean.title": "クリーンアップ中…", "clean.freed": "解放 —",
    "done.title": "クリーンアップ完了", "done.cancelled": "中断されました", "done.partial": "クリーンアップ完了（一部スキップ）",
    "done.freed.total": "合計 {0} を解放", "done.note.quarantine": "隔離ファイルは {0} 日間保持され、ツールボックスから復元できます。",
    "done.note.skip": "スキップされたファイルは他のプログラムが使用中です。終了後に再実行してください。",
    "done.stat.ok": "成功", "done.stat.quar": "隔離へ", "done.stat.skip": "スキップ（使用中）", "done.stat.fail": "失敗",
    "clean.tab.system": "システムゴミ", "clean.tab.app": "アプリキャッシュ", "clean.tab.browser": "ブラウザ",
    "clean.tab.privacy": "プライバシー痕跡", "clean.tab.recycle": "ごみ箱",
    "clean.tabnote.0": "システムとアプリの一時ファイル・ログ・クラッシュレポート。安全な項目のみ既定選択",
    "clean.tabnote.1": "チャット・オフィスアプリのキャッシュとログ。チャット記録や文書には触れません",
    "clean.tabnote.2": "閲覧を高速化するブラウザキャッシュ。ログイン・パスワード・履歴には影響しません",
    "clean.tabnote.3": "個人記録を含みます。既定で未選択。影響をよく確認してから実行してください",
    "clean.tabnote.4": "空にする前に、必要なファイルがないかごみ箱を確認してください",
    "clean.privacy.banner": "プライバシー項目は既定で未選択です。選択前に各項目の影響をお読みください：Cookie の削除でログアウトし、履歴の削除は元に戻せません。",
    "clean.privacy.warn": "プライバシー項目は削除後に復元できません。影響を理解した上で実行してください。",
    "clean.recycle.desc": "空にするとごみ箱のファイルは完全に削除され復元できません。先にごみ箱を開いて確認できます。",
    "clean.empty.before": "下の「このグループをスキャン」でチェックを開始", "clean.empty.clean": "このカテゴリはきれいです。清理対象はありません",
    "clean.empty.group": "下の「このグループをスキャン」でチェックを開始",
    "recycle.info": "{0} 項目、合計 {1}", "recycle.empty": "ごみ箱は空です",
    "recycle.confirm.title": "ごみ箱を空にしますか？", "recycle.confirm.msg": "ごみ箱の {0} 個のファイル（{1}）は完全に削除され、復元できません。",
    "toast.cleandone": "クリーンアップ完了。{0} を解放", "toast.skipped": "（{0} 件スキップ）", "toast.binemptied": "ごみ箱を空にしました",
    "toast.failed": "操作に失敗しました",
    "dlg.clean.selected.title": "選択した項目をクリーンアップしますか？", "dlg.clean.amount": "{0} のデータを清理しようとしています。",
    "dlg.clean.nrules": "{0} カテゴリ、合計 {1} を清理します。", "dlg.clean.confirmitems": "確認が必要な項目：",
    "dlg.clean.quarantinehint": "復元可能なファイルは隔離区に移動されます。",
    "dlg.quickclean.title": "{0} を清理しますか？", "dlg.quickclean.msg": "約 {0} が解放されます。\n復元可能なファイルは隔離区に移動されます。",
    "space.tab.overview": "概要", "space.tab.large": "大容量ファイル", "space.tree.title": "フォルダ使用量ランキング",
    "space.tree.hint": "クリックで展開。システムリンクとアクセス不可フォルダはスキップ",
    "space.empty": "このドライブは未解析です。右上の「解析開始」をクリック（いつでもキャンセル可）",
    "space.scanning": "ディスクを解析中…", "space.cancelled": "解析をキャンセルしました", "space.failed": "解析失敗：",
    "space.done": "解析完了（{0:F0} 秒）", "space.rendererror": "解析結果の表示に問題。ログを確認してください",
    "space.scanned": "{0:N0} ファイルを走査", "space.total": "合計 {0}",
    "space.used.f": "使用中 {0} / {1}（{2:F1}%）、空き {3}", "space.used.f2": "使用中 {0} / {1}、空き {2}",
    "space.analyzed.f": "解析 {0} · {1:N0} ファイル · {2:F0} 秒", "space.lastanalysis": "前回の解析：{0}",
    "space.notanalyzed": "このドライブはまだ解析されていません", "space.large.filter": "サイズ絞り込み",
    "space.large.none": "{0:F0} MB 超のファイルは見つかりません", "space.modified": "更新", "space.file": "FILE",
    "space.recycle.title": "ごみ箱へ移動しますか？", "space.recycle.msg": "{0}（{1}）をごみ箱へ移動します。いつでも復元できます。",
    "toast.whitelisted": "ホワイトリストに追加しました。スキャン・清理はこのファイルをスキップします",
    "toast.largecleaned": "大容量ファイル {0} を清理", "toast.recycled": "ごみ箱へ移動。{0} を解放",
    "toast.recyclefailed": "ごみ箱への移動に失敗。ファイルが使用中の可能性があります",
    "startup.desc": "無効にしてもアプリは手動で開けます。変更はすべて記録され、いつでも元に戻せます。",
    "startup.col.toggle": "状態", "startup.col.impact": "影響", "startup.col.source": "ソース", "startup.col.suggest": "提案",
    "startup.loading": "スタートアップ項目を読み込み中…", "startup.empty": "一致する項目がありません", "startup.systemchip": "システムコンポーネント",
    "startup.src.reghkcu": "レジストリ (現在のユーザー)", "startup.src.reghklm": "レジストリ (マシン)",
    "startup.src.folderuser": "スタートアップフォルダ (ユーザー)", "startup.src.foldercommon": "スタートアップフォルダ (全ユーザー)",
    "startup.src.task": "スケジュールタスク", "startup.impact.high": "高", "startup.impact.med": "中",
    "startup.impact.low": "低", "startup.impact.unknown": "未評価",
    "startup.suggest.off": "無効化を検討", "startup.suggest.system": "システムコンポーネント", "startup.suggest.keep": "維持",
    "startup.enabled": "有効化", "startup.disabled": "無効化", "startup.toggled": "スタートアップ「{1}」を{0}",
    "apps.desc": "アンインストールにはアプリ自身のアンインストーラーを使用。完了後、確認された残存ファイルを清理できます（隔離区、復元可）。",
    "apps.sort.name": "名前順", "apps.sort.size": "サイズ順", "apps.sort.date": "インストール日順",
    "apps.col.name": "アプリ", "apps.col.publisher": "発行元", "apps.col.size": "サイズ", "apps.col.date": "インストール日",
    "apps.loading": "インストール済みアプリを読み込み中…", "apps.empty": "一致するアプリがありません", "apps.store": "Microsoft Store アプリ",
    "apps.unknown": "不明", "apps.uninstall.title": "{0} をアンインストールしますか？", "apps.uninstall.start": "アンインストール開始",
    "apps.uninstall.msg": "アプリサイズ：{0}\n\nアプリ自身のアンインストーラーを起動します。ウィザードに従って完了してください。",
    "apps.waiting": "「{0}」のアンインストールを待機中…\n完了すると自動的に続行します",
    "apps.notdetected": "アンインストールを検出できませんでした。キャンセルされた可能性があります",
    "apps.uninstalled.toast": "「{0}」をアンインストールしました", "apps.uninstalled.log": "アプリ「{0}」をアンインストール",
    "apps.uninstall.failed": "アンインストーラーを起動できません：",
    "leftover.title": "残存ファイルの可能性", "leftover.title.f": "「{0}」の残存ファイル",
    "leftover.desc": "このアプリに属すると確認できるデータフォルダと設定キーです。選択した項目は隔離区へ移動され復元可能です。",
    "leftover.skip": "清理せず終了", "leftover.clean": "選択項目を清理", "leftover.reg": "設定レジストリキー（バックアップ後に削除）",
    "leftover.datadir": "データフォルダ", "leftover.installdir": "インストールフォルダ",
    "tool.desc": "シュレッドしたファイルはごみ箱を経由しません。隔離ファイルはいつでも復元可能。重複検出は内容ハッシュベースです。",
    "tool.quarantine.title": "隔離区", "tool.quar.empty": "隔離区は空です",
    "tool.quar.summary": "{0} 項目、合計 {1}。{2} 日後に自動削除",
    "tool.quar.daysleft": "残り {0} 日", "tool.purge.title": "隔離区を空にしますか？",
    "tool.purge.msg": "隔離区の {0} 項目を完全に削除します。元に戻せません。",
    "tool.shred.title": "ファイルシュレッダー", "tool.shred.desc": "ごみ箱を経由せずファイルを完全削除します。SSD では物理的な即時上書きは保証できません。復元不可のため、ファイルの選択は慎重に。",
    "tool.shred.confirm.title": "シュレッドしますか？", "tool.shred.confirm.msg": "{0}\n\n{1} を上書き後、完全に削除します。ごみ箱を経由せず、ソフトウェアでの復元は困難です。\n\nこの操作は取り消せません！",
    "tool.shred.log": "{0}「{1}」をシュレッド", "tool.folder": "フォルダ", "tool.file": "ファイル",
    "tool.dup.title": "重複ファイル", "tool.dup.desc": "内容ハッシュで重複を確認（ファイル名照合ではありません）。既定の範囲はピクチャ・ビデオ・ダウンロードです。",
    "tool.dup.none": "重複ファイルは見つかりません", "tool.dup.summary": "{0} グループの重複。{1} 解放可能",
    "tool.dup.progress": "{0:N0} ファイルを走査…", "tool.dup.more": "… 他 {0} グループは未表示",
    "tool.dup.group": "{0} 個の同一ファイル · 各 {1} · {2} 解放可能", "tool.dup.tip": "チェック = このコピーを削除",
    "tool.dup.clean.title": "選択したコピーを削除しますか？", "tool.dup.clean.msg": "{0} ファイル（{1}）をごみ箱へ移動します（復元可能）。",
    "tool.history.title": "履歴", "tool.win.title": "Windows ツール", "tool.win.desc": "標準システムツールへのショートカット。安全です",
    "tool.win.taskmgr": "タスクマネージャー", "tool.win.taskmgr.d": "プロセスとパフォーマンス",
    "tool.win.storage": "ストレージ設定", "tool.win.storage.d": "ストレージの管理",
    "tool.win.diskmgmt": "ディスクの管理", "tool.win.diskmgmt.d": "パーティションとディスクの管理",
    "tool.win.devmgmt": "デバイスマネージャー", "tool.win.devmgmt.d": "ハードウェアとドライバーの管理",
    "tool.win.control": "コントロールパネル", "tool.win.control.d": "従来のシステム設定",
    "tool.win.msinfo": "システム情報", "tool.win.msinfo.d": "システム構成の確認",
    "tool.win.update": "Windows Update", "tool.win.update.d": "システム更新の確認",
    "tool.win.restore": "システムの復元", "tool.win.restore.d": "復元ポイントの作成と使用",
    "history.empty": "履歴はまだありません", "history.clear.title": "履歴を消去しますか？", "history.clear.msg": "すべての記録が削除されます。",
    "history.type.clean": "清理", "history.type.autoclean": "自動清理", "history.type.restore": "復元",
    "history.type.uninstall": "アンインストール", "history.type.startup": "スタートアップ", "history.type.quarantine": "隔離区",
    "history.type.shred": "シュレッド", "history.type.other": "その他",
    "settings.title": "設定", "settings.sec.general": "全般", "settings.sec.exclude": "除外とホワイトリスト",
    "settings.sec.notify": "通知", "settings.sec.advanced": "詳細", "settings.sec.privacy": "プライバシー", "settings.sec.about": "このアプリについて",
    "settings.exc.desc": "これらのフォルダとファイルはすべてのスキャン・清理でスキップされます。", "settings.exc.empty": "除外・ホワイトリストは未設定",
    "settings.whitelist": "ホワイトリスト", "settings.excluded": "除外",
    "settings.btn.addexclude": "除外フォルダを追加", "settings.btn.addwhitelist": "ホワイトリストに追加",
    "settings.pick.whitelist": "ホワイトリストに追加するファイルを選択", "settings.pick.exclude": "スキャン対象外にするフォルダを選択",
    "settings.days": "日", "settings.threads": "スレッド",
    "settings.theme.light": "ライト", "settings.theme.dark": "ダーク", "settings.theme.system": "システムに従う",
    "settings.freq.daily": "毎日", "settings.freq.weekly": "毎週", "settings.freq.monthly": "毎月",
    "settings.lang.auto": "システム言語に従う",
    "settings.row.language": "表示言語", "settings.row.language.d": "すぐに反映されます",
    "settings.row.autostart": "Windows 起動時に実行", "settings.row.autostart.d": "起動後はトレイで待機し、自動では何もしません",
    "settings.row.mintotray": "最小化でトレイへ", "settings.row.mintotray.d": "最小化ボタンでトレイに隠れます",
    "settings.row.closetotray": "閉じるでトレイへ", "settings.row.closetotray.d": "閉じるボタンで確認して最小化します（終了ではありません）",
    "settings.row.theme": "テーマ",
    "settings.row.quarantine": "清理後に隔離", "settings.row.quarantine.d": "キャッシュ以外のファイルは先に隔離され復元可能（推奨）",
    "settings.row.quarantine.days": "隔離保持期間", "settings.row.quarantine.days.d": "期限を過ぎると自動的に完全削除",
    "settings.row.autoclean": "自動クリーンアップ", "settings.row.autoclean.d": "一時ファイルやキャッシュなど安全な項目を定期清理",
    "settings.row.autoclean.freq": "自動清理の頻度", "settings.row.autoclean.freq.d": "アプリ起動中にバックグラウンドで実行",
    "settings.row.notifydisk": "空き容量不足の警告", "settings.row.notifydisk.d": "システムドライブの空きが 10% 未満で通知（控えめ）",
    "settings.row.notifyauto": "自動清理の結果通知", "settings.row.notifyweekly": "週次レポート",
    "settings.row.notifynews": "製品情報", "settings.row.notifynews.d": "新機能やイベントのお知らせ（既定オフ）",
    "settings.row.threads": "スキャンスレッド数", "settings.row.threads.d": "多いほど高速。HDD では少なめを推奨",
    "settings.row.hidden": "隠しファイルをスキャン", "settings.row.junction": "ディレクトリリンクを追跡 (Junction)",
    "settings.row.junction.d": "リンク追跡は二重計上の原因になります。既定オフ",
    "settings.row.stats": "匿名利用統計", "settings.row.stats.d": "機能利用回数とエラーコードのみ。このビルドでは一切送信しません",
    "settings.row.crash": "クラッシュレポート",
    "settings.privacy.desc": "スキャンデータはすべてこの端末に保存されます。ファイル名・パス・内容を収集・送信することはありません。",
    "settings.about.slogan": "明快に清理、安心して最適化。", "settings.about.support": "サポートとフィードバック",
    "settings.about.site": "公式サイト", "settings.about.email": "メール", "settings.about.repo": "ソースコード",
    "settings.about.wechat": "WeChat で「AI虚拟助理」を検索するとヒントや更新情報が届きます。",
    "wizard.welcome": "CleanMaster へようこそ",
    "wizard.slogan": "明快に清理、安心して最適化。\n説明可能・プレビュー可能・復元可能なクリーンアップだけを行います。",
    "wizard.privacy.title": "プライバシーのお約束",
    "wizard.privacy.items": "· スキャン結果・ファイル名・パスはこの PC の外に出ません。\n· テレメトリは既定オフ。ファイル内容をアップロードすることはありません。\n· 重要な清理は隔離区へ。7〜30 日間いつでも復元できます。\n· 削除前には必ずプレビュー。静かに削除されることはありません。",
    "wizard.auto.title": "自動クリーンアップを有効にしますか？", "wizard.auto.desc": "一時ファイルやアプリキャッシュなど安全な項目のみ、週 1 回清理します。",
    "wizard.auto.yes": "有効にする", "wizard.auto.no": "今はしない", "wizard.next": "始める", "wizard.next2": "次へ",
    "tray.open": "CleanMaster を開く", "tray.quickscan": "クイックスキャン", "tray.exit": "終了",
    "tray.autoclean": "自動清理：", "tray.on": "オン", "tray.off": "オフ",
    "dlg.exit.title": "CleanMaster を終了しますか？", "dlg.exit.msg": "終了すると自動清理とディスク監視は停止します。",
    "toast.traymin": "トレイに最小化しました。トレイアイコンを右クリックで終了できます",
    "toast.scanstopped": "スキャンを停止しました", "toast.scanfailed": "スキャン失敗：", "toast.noselect": "先に清理する項目を選択してください",
    "toast.cleancancelled": "クリーンアップをキャンセルしました", "toast.cleanfailed": "クリーンアップ失敗：",
    "toast.nothing": "清理できる項目は見つかりません", "toast.cleaned": "クリーンアップ完了。{0} を解放",
    "toast.readfailed": "読み込み失敗：", "toast.langapplied": "表示言語を切り替えました",
}

KO = {
    "common.selected": "선택됨", "common.freeable": "확보 가능", "common.viewall": "모두 보기",
    "common.loading": "불러오는 중…", "common.scanning": "스캔 중…", "common.n.items": "{0}개 항목",
    "common.approx": "약 ", "btn.cancel": "취소", "btn.exit": "종료", "btn.refresh": "새로 고침",
    "btn.stopscan": "스캔 중지", "btn.rescan": "다시 스캔", "btn.restore": "복원", "btn.deleteperm": "영구 삭제",
    "btn.uninstall": "제거", "btn.recycle": "휴지통으로 이동", "btn.remove": "제거", "btn.analyze.start": "분석 시작",
    "btn.scan.now": "지금 스캔", "btn.more": "더보기", "btn.clean.selected": "선택 항목 정리",
    "btn.clean.start": "정리 시작", "btn.done.home": "홈으로", "btn.done.quarantine": "격리소 열기",
    "btn.emptybin": "휴지통 비우기", "btn.openbin": "휴지통 열기", "btn.scangroup": "이 그룹 스캔",
    "btn.cleansel": "선택 항목 정리", "btn.dupscan": "스캔 시작", "btn.dup.rescan": "다시 스캔",
    "btn.dupkeepnew": "최신 항목 유지, 나머지 선택", "btn.dupclean": "선택 항목을 휴지통으로",
    "btn.clearhistory": "기록 비우기", "btn.clearlocal": "로컬 기록 지우기", "btn.purge": "격리소 비우기",
    "btn.shredfile": "파일 완전 삭제", "btn.shreddir": "폴더 완전 삭제", "btn.shred": "완전 삭제 실행",
    "tip.min": "최소화", "tip.max": "최대화", "tip.close": "닫기",
    "nav.home": "홈", "nav.scan": "스마트 스캔", "nav.clean": "정리 공간", "nav.space": "공간 분석",
    "nav.startup": "시작 프로그램", "nav.apps": "앱 관리", "nav.toolbox": "도구", "nav.settings": "설정",
    "risk.safe": "안전", "risk.low": "낮은 위험", "risk.confirm": "확인 필요", "risk.high": "높은 위험",
    "cat.system": "시스템", "cat.apps": "앱", "cat.images": "이미지", "cat.videos": "동영상",
    "cat.audio": "음악", "cat.documents": "문서", "cat.archives": "압축 파일", "cat.other": "기타",
    "time.now": "방금", "time.minago": "{0}분 전", "time.today": "오늘 {0}", "time.yesterday": "어제 {0}",
    "home.slogan": "정기적인 스캔으로 PC를 최상의 상태로 유지하세요",
    "home.status.good": "장치 상태 양호", "home.status.suggest": "정리를 권장합니다", "home.status.tight": "디스크 공간 부족",
    "home.status.suggest.detail": "정리 가능한 데이터 {0} 및 고영향 시작 프로그램 {1}개 발견",
    "home.status.tight.detail": "시스템 드라이브 여유 공간이 10% 미만입니다. 지금 정리하세요",
    "home.status.lastscan": "마지막 스캔: {0}", "home.noscan": "아직 스캔하지 않음", "home.noscan.detail": "「지금 스캔」을 눌러 시작하세요",
    "home.card.junk": "정리 가능한 데이터", "home.card.junk.note": "스캔하여 확보 가능 공간 확인", "home.card.junk.lastscan": "마지막 스캔 {0}",
    "home.card.startup": "시작 프로그램", "home.card.startup.note": "개 프로그램이 부팅 시 실행", "home.card.startup.note.high": "고영향 항목이 부팅을 늦출 수 있음",
    "home.card.large": "대용량 파일", "home.card.large.note": "분석하여 찾기", "home.card.large.analyzed": "분석됨",
    "home.card.large.analyzed.note": "클릭하여 대용량 파일 보기", "home.card.large.pending": "대기 중",
    "home.card.apps": "설치된 앱", "home.card.apps.note": "클릭하여 관리",
    "home.disk.title": "디스크 공간 (C:)", "home.disk.title.disk": "디스크 공간 ({0})", "home.disk.total": "전체 —",
    "home.disk.used": "사용 중 —", "home.disk.free": "여유 —", "home.disk.total.f": "전체 {0}",
    "home.disk.used.f": "사용 {0} ({1:F1}%)", "home.disk.free.f": "여유 {0} ({1:F1}%)", "home.disk.more": "공간이 어디로 갔을까 →",
    "home.space.title": "공간 분석", "home.space.empty": "이 드라이브는 아직 분석되지 않았습니다",
    "home.activity.title": "최근 활동", "home.activity.empty": "기록이 없습니다. 스캔을 시작해 보세요",
    "home.suggest.title": "스마트 제안", "home.suggest.empty": "문제없습니다. 처리할 항목이 없습니다",
    "home.suggest.note.safe": "안전하게 정리 가능하며 시스템에 영향이 없습니다", "home.suggest.clean": "지금 정리", "home.suggest.optimize": "최적화",
    "home.suggest.startup.title": "시작 프로그램 제안", "home.suggest.startup.note": "고영향 시작 프로그램 {0}개 발견. 최적화를 권장합니다",
    "home.hero.note": "더 깨끗한 PC,\n더 부드러운 실행!",
    "scan.start": "스캔 시작", "scan.cover": "한 번에 스캔: 시스템 데이터 · 브라우저 캐시 · 앱 캐시 · 휴지통",
    "scan.privacy": "모두 로컬에서 실행됩니다. 안전한 항목만 기본 선택되며 위험 항목은 자동 선택되지 않습니다.",
    "scan.preparing": "준비 중…", "scan.found": "발견 —", "scan.done": "스캔 완료", "scan.reselectall": "안전 항목 선택",
    "scan.group.safe": "안전하게 정리 가능", "scan.group.safe.note": "시스템과 앱이 만든 임시 데이터. 삭제해도 안전합니다",
    "scan.group.cache": "브라우저·앱 캐시", "scan.group.cache.note": "캐시 데이터. 앱이 필요 시 다시 받습니다",
    "scan.group.check": "확인 필요", "scan.group.check.note": "정리 전에 더 이상 필요 없는지 확인하세요",
    "result.title.found": "스캔 완료 — {0} 확보 가능", "result.title.clean": "스캔 완료 — 매우 깨끗합니다!",
    "result.sub": "{0} · {1}개 카테고리 스캔",
    "row.files": "파일 {0}개", "row.restore": "격리를 통해 복원 가능", "row.direct": "직접 삭제",
    "row.running": "관련 프로세스 {0}개 실행 중", "row.impact.tip": "정리 영향: {0}",
    "clean.title": "정리 중…", "clean.freed": "확보 —",
    "done.title": "정리 완료", "done.cancelled": "정리가 중단되었습니다", "done.partial": "정리 완료(일부 건너뜀)",
    "done.freed.total": "총 {0} 확보", "done.note.quarantine": "격리 파일은 {0}일간 보관되며 도구에서 복원할 수 있습니다.",
    "done.note.skip": "건너뛴 파일은 다른 프로그램이 사용 중입니다. 종료 후 다시 시도하세요.",
    "done.stat.ok": "성공", "done.stat.quar": "격리됨", "done.stat.skip": "건너뜀(사용 중)", "done.stat.fail": "실패",
    "clean.tab.system": "시스템 데이터", "clean.tab.app": "앱 캐시", "clean.tab.browser": "브라우저",
    "clean.tab.privacy": "개인정보 흔적", "clean.tab.recycle": "휴지통",
    "clean.tabnote.0": "시스템·앱의 임시 파일, 로그, 크래시 리포트. 안전한 항목만 기본 선택",
    "clean.tabnote.1": "메신저·오피스 앱의 캐시와 로그. 대화 내용과 문서는 건드리지 않습니다",
    "clean.tabnote.2": "브라우징 속도를 위한 캐시. 로그인·비밀번호·기록에 영향 없음",
    "clean.tabnote.3": "개인 기록 포함. 기본 모두 선택 해제. 영향을 확인 후 진행하세요",
    "clean.tabnote.4": "비우기 전에 필요한 파일이 없는지 확인하세요",
    "clean.privacy.banner": "개인정보 항목은 기본 선택 해제 상태입니다. 선택 전 각 항목의 영향을 읽어주세요: 쿠키 삭제 시 로그아웃되고 기록 삭제는 되돌릴 수 없습니다.",
    "clean.privacy.warn": "개인정보 항목은 정리 후 복원할 수 없습니다. 영향을 이해했는지 확인하세요.",
    "clean.recycle.desc": "비우면 휴지통의 파일이 영구 삭제되어 복원할 수 없습니다. 먼저 휴지통을 열어 확인할 수 있습니다.",
    "clean.empty.before": "아래의 「이 그룹 스캔」을 눌러 확인을 시작하세요", "clean.empty.clean": "이 카테고리는 깨끗합니다. 정리할 항목이 없습니다",
    "clean.empty.group": "아래의 「이 그룹 스캔」을 눌러 확인을 시작하세요",
    "recycle.info": "{0}개 항목, {1} 사용", "recycle.empty": "휴지통이 비어 있습니다",
    "recycle.confirm.title": "휴지통을 비울까요?", "recycle.confirm.msg": "휴지통의 {0}개 파일({1})이 영구 삭제되며 복원할 수 없습니다.",
    "toast.cleandone": "정리 완료 — {0} 확보", "toast.skipped": " ({0}개 건너뜀)", "toast.binemptied": "휴지통을 비웠습니다",
    "toast.failed": "작업 실패",
    "dlg.clean.selected.title": "선택한 항목을 정리할까요?", "dlg.clean.amount": "{0}의 데이터를 정리합니다.",
    "dlg.clean.nrules": "{0}개 카테고리, 총 {1}을 정리합니다.", "dlg.clean.confirmitems": "확인이 필요한 항목:",
    "dlg.clean.quarantinehint": "복원 가능한 파일은 격리소로 이동됩니다.",
    "dlg.quickclean.title": "{0}을(를) 정리할까요?", "dlg.quickclean.msg": "약 {0}이 확보됩니다.\n복원 가능한 파일은 격리소로 이동됩니다.",
    "space.tab.overview": "개요", "space.tab.large": "대용량 파일", "space.tree.title": "폴더 사용량 순위",
    "space.tree.hint": "클릭하여 펼치기. 시스템 링크와 접근 불가 폴더는 건너뜁니다",
    "space.empty": "이 드라이브는 아직 분석되지 않았습니다. 오른쪽 위 「분석 시작」을 누르세요(언제든 취소 가능)",
    "space.scanning": "디스크 분석 중…", "space.cancelled": "분석이 취소되었습니다", "space.failed": "분석 실패: ",
    "space.done": "분석 완료({0:F0}초)", "space.rendererror": "분석 결과 표시에 문제가 있습니다. 로그를 확인하세요",
    "space.scanned": "{0:N0}개 파일 스캔", "space.total": "총 {0}",
    "space.used.f": "사용 {0} / {1}({2:F1}%), 여유 {3}", "space.used.f2": "사용 {0} / {1}, 여유 {2}",
    "space.analyzed.f": "분석 {0} · {1:N0}개 파일 · {2:F0}초", "space.lastanalysis": "마지막 분석: {0}",
    "space.notanalyzed": "이 드라이브는 아직 분석되지 않았습니다", "space.large.filter": "크기 필터",
    "space.large.none": "{0:F0} MB 초과 파일이 없습니다", "space.modified": "수정", "space.file": "파일",
    "space.recycle.title": "휴지통으로 이동할까요?", "space.recycle.msg": "{0}({1})을(를) 휴지통으로 이동합니다. 언제든 복원할 수 있습니다.",
    "toast.whitelisted": "화이트리스트에 추가했습니다. 스캔과 정리에서 이 파일은 건너뜁니다",
    "toast.largecleaned": "대용량 파일 {0} 정리", "toast.recycled": "휴지통으로 이동 — {0} 확보",
    "toast.recyclefailed": "휴지통 이동 실패. 파일이 사용 중일 수 있습니다",
    "startup.desc": "비활성화해도 앱은 수동으로 열 수 있습니다. 모든 변경은 기록되어 언제든 되돌릴 수 있습니다.",
    "startup.col.toggle": "상태", "startup.col.impact": "영향", "startup.col.source": "원본", "startup.col.suggest": "제안",
    "startup.loading": "시작 프로그램을 읽는 중…", "startup.empty": "일치하는 항목이 없습니다", "startup.systemchip": "시스템 구성 요소",
    "startup.src.reghkcu": "레지스트리 (현재 사용자)", "startup.src.reghklm": "레지스트리 (컴퓨터)",
    "startup.src.folderuser": "시작 폴더 (사용자)", "startup.src.foldercommon": "시작 폴더 (모든 사용자)",
    "startup.src.task": "예약 작업", "startup.impact.high": "높음", "startup.impact.med": "중간",
    "startup.impact.low": "낮음", "startup.impact.unknown": "미측정",
    "startup.suggest.off": "끄기 고려", "startup.suggest.system": "시스템 구성 요소", "startup.suggest.keep": "유지",
    "startup.enabled": "사용", "startup.disabled": "사용 안 함", "startup.toggled": "시작 프로그램 「{1}」 {0}",
    "apps.desc": "제거 시 앱 자체 제거 프로그램을 실행합니다. 완료 후 확인된 잔여 파일을 정리할 수 있습니다(격리소, 복원 가능).",
    "apps.sort.name": "이름순", "apps.sort.size": "크기순", "apps.sort.date": "설치일순",
    "apps.col.name": "앱", "apps.col.publisher": "게시자", "apps.col.size": "크기", "apps.col.date": "설치 날짜",
    "apps.loading": "설치된 앱을 읽는 중…", "apps.empty": "일치하는 앱이 없습니다", "apps.store": "Microsoft Store 앱",
    "apps.unknown": "알 수 없음", "apps.uninstall.title": "{0}을(를) 제거할까요?", "apps.uninstall.start": "제거 시작",
    "apps.uninstall.msg": "앱 크기: {0}\n\n앱 자체 제거 프로그램이 실행됩니다. 마법사를 따라 완료해 주세요.",
    "apps.waiting": "「{0}」 제거 완료 대기 중…\n완료되면 자동으로 계속됩니다",
    "apps.notdetected": "제거 완료를 감지하지 못했습니다. 취소되었을 수 있습니다",
    "apps.uninstalled.toast": "「{0}」 제거됨", "apps.uninstalled.log": "앱 「{0}」 제거",
    "apps.uninstall.failed": "제거 프로그램 실행 실패: ",
    "leftover.title": "잔여 파일 발견", "leftover.title.f": "「{0}」의 잔여 파일",
    "leftover.desc": "이 앱에 속한 것으로 확인된 데이터 폴더와 설정 키입니다. 선택 항목은 격리소로 이동되어 복원 가능합니다.",
    "leftover.skip": "정리하지 않고 완료", "leftover.clean": "선택 항목 정리", "leftover.reg": "설정 레지스트리 키(백업 후 삭제)",
    "leftover.datadir": "데이터 폴더", "leftover.installdir": "설치 폴더",
    "tool.desc": "완전 삭제된 파일은 휴지통을 거치지 않습니다. 격리 파일은 언제든 복원 가능. 중복 검출은 내용 해시 기반입니다.",
    "tool.quarantine.title": "격리소", "tool.quar.empty": "격리소가 비어 있습니다",
    "tool.quar.summary": "{0}개 항목, {1}. {2}일 후 자동 삭제",
    "tool.quar.daysleft": "{0}일 남음", "tool.purge.title": "격리소를 비울까요?",
    "tool.purge.msg": "격리소의 {0}개 항목이 영구 삭제됩니다. 되돌릴 수 없습니다.",
    "tool.shred.title": "파일 완전 삭제", "tool.shred.desc": "휴지통을 거치지 않고 파일을 영구 삭제합니다. SSD에서는 물리적 즉시 덮어쓰기가 보장되지 않습니다. 되돌릴 수 없으니 신중히 선택하세요.",
    "tool.shred.confirm.title": "완전 삭제할까요?", "tool.shred.confirm.msg": "{0}\n\n{1}을(를) 덮어쓴 후 영구 삭제합니다. 휴지통을 거치지 않으며 복구 소프트웨어로도 쉽게 복원되지 않습니다.\n\n이 작업은 되돌릴 수 없습니다!",
    "tool.shred.log": "{0} 「{1}」 완전 삭제", "tool.folder": "폴더", "tool.file": "파일",
    "tool.dup.title": "중복 파일", "tool.dup.desc": "내용 해시로 중복을 확인합니다(파일명 비교 아님). 기본 범위는 사진·비디오·다운로드입니다.",
    "tool.dup.none": "중복 파일이 없습니다", "tool.dup.summary": "중복 그룹 {0}개, {1} 확보 가능",
    "tool.dup.progress": "{0:N0}개 파일 스캔…", "tool.dup.more": "… {0}개 그룹 더 있음",
    "tool.dup.group": "동일 파일 {0}개 · 각 {1} · {2} 확보 가능", "tool.dup.tip": "체크 = 이 복사본 삭제",
    "tool.dup.clean.title": "선택한 복사본을 삭제할까요?", "tool.dup.clean.msg": "{0}개 파일({1})을 휴지통으로 이동합니다(복원 가능).",
    "tool.history.title": "정리 기록", "tool.win.title": "Windows 도구", "tool.win.desc": "기본 제공 시스템 도구로 바로 가기. 안전합니다",
    "tool.win.taskmgr": "작업 관리자", "tool.win.taskmgr.d": "프로세스와 성능 보기",
    "tool.win.storage": "저장소 설정", "tool.win.storage.d": "저장소 관리",
    "tool.win.diskmgmt": "디스크 관리", "tool.win.diskmgmt.d": "파티션과 디스크 관리",
    "tool.win.devmgmt": "장치 관리자", "tool.win.devmgmt.d": "하드웨어와 드라이버 관리",
    "tool.win.control": "제어판", "tool.win.control.d": "클래식 시스템 설정",
    "tool.win.msinfo": "시스템 정보", "tool.win.msinfo.d": "시스템 구성 보기",
    "tool.win.update": "Windows 업데이트", "tool.win.update.d": "시스템 업데이트 확인",
    "tool.win.restore": "시스템 복원", "tool.win.restore.d": "복원 지점 만들기/사용",
    "history.empty": "기록이 없습니다", "history.clear.title": "기록을 비울까요?", "history.clear.msg": "모든 정리·작업 기록이 삭제됩니다.",
    "history.type.clean": "정리", "history.type.autoclean": "자동 정리", "history.type.restore": "복원",
    "history.type.uninstall": "제거", "history.type.startup": "시작 프로그램", "history.type.quarantine": "격리소",
    "history.type.shred": "완전 삭제", "history.type.other": "기타",
    "settings.title": "설정", "settings.sec.general": "일반", "settings.sec.exclude": "제외·화이트리스트",
    "settings.sec.notify": "알림", "settings.sec.advanced": "고급", "settings.sec.privacy": "개인정보", "settings.sec.about": "정보",
    "settings.exc.desc": "이 폴더와 파일은 모든 스캔·정리에서 건너뛰어집니다.", "settings.exc.empty": "제외·화이트리스트 항목 없음",
    "settings.whitelist": "화이트리스트", "settings.excluded": "제외",
    "settings.btn.addexclude": "제외 폴더 추가", "settings.btn.addwhitelist": "화이트리스트 파일/폴더 추가",
    "settings.pick.whitelist": "화이트리스트에 추가할 파일 선택", "settings.pick.exclude": "스캔에서 제외할 폴더 선택",
    "settings.days": "일", "settings.threads": "스레드",
    "settings.theme.light": "라이트", "settings.theme.dark": "다크", "settings.theme.system": "시스템 따르기",
    "settings.freq.daily": "매일", "settings.freq.weekly": "매주", "settings.freq.monthly": "매월",
    "settings.lang.auto": "시스템 언어 따르기",
    "settings.row.language": "인터페이스 언어", "settings.row.language.d": "즉시 적용됩니다",
    "settings.row.autostart": "Windows 시작 시 실행", "settings.row.autostart.d": "부팅 후 트레이에서 대기만 하며 자동으로 아무 작업도 하지 않습니다",
    "settings.row.mintotray": "트레이로 최소화", "settings.row.mintotray.d": "최소화 버튼으로 트레이에 숨겨집니다",
    "settings.row.closetotray": "닫기 버튼으로 트레이 최소화", "settings.row.closetotray.d": "닫기 버튼 시 확인 후 최소화합니다(종료 아님)",
    "settings.row.theme": "테마",
    "settings.row.quarantine": "정리 후 격리", "settings.row.quarantine.d": "캐시가 아닌 파일은 먼저 격리되어 복원 가능(권장)",
    "settings.row.quarantine.days": "격리 보관 기간", "settings.row.quarantine.days.d": "만료 후 자동 영구 삭제",
    "settings.row.autoclean": "자동 정리", "settings.row.autoclean.d": "임시 파일·캐시 등 안전한 항목을 주기적으로 정리",
    "settings.row.autoclean.freq": "자동 정리 주기", "settings.row.autoclean.freq.d": "앱 실행 중 백그라운드에서 수행",
    "settings.row.notifydisk": "디스크 부족 알림", "settings.row.notifydisk.d": "시스템 드라이브 여유가 10% 미만이면 알림(드묾)",
    "settings.row.notifyauto": "자동 정리 결과 알림", "settings.row.notifyweekly": "주간 보고서",
    "settings.row.notifynews": "제품 소식", "settings.row.notifynews.d": "새 기능·이벤트 알림(기본 꺼짐)",
    "settings.row.threads": "스캔 스레드 수", "settings.row.threads.d": "많을수록 빠릅니다. HDD에서는 줄이세요",
    "settings.row.hidden": "숨김 파일 스캔", "settings.row.junction": "디렉터리 링크 따라가기 (Junction)",
    "settings.row.junction.d": "링크 추적은 중복 집계를 유발할 수 있습니다. 기본 꺼짐",
    "settings.row.stats": "익명 통계", "settings.row.stats.d": "기능 사용 수와 오류 코드만 전송 대상. 이 빌드는 아무것도 전송하지 않습니다",
    "settings.row.crash": "크래시 리포트",
    "settings.privacy.desc": "모든 스캔 데이터는 이 PC에만 저장됩니다. 파일명·경로·내용을 수집하거나 전송하지 않습니다.",
    "settings.about.slogan": "명확하게 정리, 안심하고 최적화.", "settings.about.support": "지원 및 피드백",
    "settings.about.site": "지원 사이트", "settings.about.email": "이메일", "settings.about.repo": "소스 코드",
    "settings.about.wechat": "WeChat에서 「AI虚拟助理」을 검색하면 팁과 소식을 받을 수 있습니다.",
    "wizard.welcome": "CleanMaster에 오신 것을 환영합니다",
    "wizard.slogan": "명확하게 정리, 안심하고 최적화.\n설명 가능·미리보기 가능·복원 가능한 정리만 제공합니다.",
    "wizard.privacy.title": "개인정보 약속",
    "wizard.privacy.items": "· 스캔 결과, 파일명, 경로는 이 PC 밖으로 나가지 않습니다.\n· 텔레메트리는 기본 꺼짐. 파일 내용을 업로드하지 않습니다.\n· 주요 정리는 격리소로 이동. 7~30일간 복원 가능합니다.\n· 삭제 전 반드시 미리보기. 몰래 삭제하지 않습니다.",
    "wizard.auto.title": "자동 정리를 켤까요?", "wizard.auto.desc": "임시 파일·앱 캐시 등 안전한 항목만 매주 정리합니다.",
    "wizard.auto.yes": "자동 정리 켜기", "wizard.auto.no": "나중에", "wizard.next": "시작하기", "wizard.next2": "다음",
    "tray.open": "CleanMaster 열기", "tray.quickscan": "빠른 스캔", "tray.exit": "종료",
    "tray.autoclean": "자동 정리: ", "tray.on": "켬", "tray.off": "끔",
    "dlg.exit.title": "CleanMaster를 종료할까요?", "dlg.exit.msg": "종료하면 자동 정리와 디스크 모니터링이 중지됩니다.",
    "toast.traymin": "트레이로 최소화했습니다. 트레이 아이콘 우클릭으로 종료할 수 있습니다",
    "toast.scanstopped": "스캔이 중지되었습니다", "toast.scanfailed": "스캔 실패: ", "toast.noselect": "먼저 정리할 항목을 선택하세요",
    "toast.cleancancelled": "정리가 취소되었습니다", "toast.cleanfailed": "정리 실패: ",
    "toast.nothing": "정리할 항목이 없습니다", "toast.cleaned": "정리 완료 — {0} 확보",
    "toast.readfailed": "불러오기 실패: ", "toast.langapplied": "인터페이스 언어가 변경되었습니다",
}
