# -*- coding: utf-8 -*-
"""繁體中文（zh-TW）。"""

ZH_TW = {
    "common.selected": "已選擇", "common.freeable": "可釋放", "common.viewall": "查看全部",
    "common.loading": "正在讀取…", "common.scanning": "正在掃描…", "common.n.items": "{0} 項",
    "common.approx": "約 ", "btn.cancel": "取消", "btn.exit": "結束", "btn.refresh": "重新整理",
    "btn.stopscan": "停止掃描", "btn.rescan": "重新掃描", "btn.restore": "還原", "btn.deleteperm": "永久刪除",
    "btn.uninstall": "解除安裝", "btn.recycle": "移至資源回收筒", "btn.remove": "移除", "btn.analyze.start": "開始分析",
    "btn.scan.now": "立即掃描", "btn.more": "更多功能", "btn.clean.selected": "清理已選項目",
    "btn.clean.start": "開始清理", "btn.done.home": "返回首頁", "btn.done.quarantine": "開啟隔離區",
    "btn.emptybin": "清空資源回收筒", "btn.openbin": "開啟資源回收筒", "btn.scangroup": "掃描此分類",
    "btn.cleansel": "清理所選項目", "btn.dupscan": "開始掃描", "btn.dup.rescan": "重新掃描",
    "btn.dupkeepnew": "保留最新，選取其餘", "btn.dupclean": "將所選移至資源回收筒",
    "btn.clearhistory": "清空歷史", "btn.clearlocal": "清除本機歷史記錄", "btn.purge": "清空隔離區",
    "btn.shredfile": "選擇檔案粉碎", "btn.shreddir": "選擇資料夾粉碎", "btn.shred": "永久粉碎",
    "tip.min": "最小化", "tip.max": "最大化", "tip.close": "關閉",
    "nav.home": "首頁", "nav.scan": "智慧掃描", "nav.clean": "清理空間", "nav.space": "空間分析",
    "nav.startup": "啟動項", "nav.apps": "應用程式管理", "nav.toolbox": "工具箱", "nav.settings": "設定",
    "risk.safe": "安全", "risk.low": "低風險", "risk.confirm": "需確認", "risk.high": "高風險",
    "cat.system": "系統", "cat.apps": "應用", "cat.images": "圖片", "cat.videos": "影片",
    "cat.audio": "音訊", "cat.documents": "文件", "cat.archives": "壓縮檔", "cat.other": "其他",
    "time.now": "剛剛", "time.minago": "{0} 分鐘前", "time.today": "今天 {0}", "time.yesterday": "昨天 {0}",
    "home.slogan": "保持定期掃描，讓電腦始終保持最佳狀態",
    "home.status.good": "裝置狀態良好", "home.status.suggest": "建議清理一下", "home.status.tight": "磁碟空間不足",
    "home.status.suggest.detail": "發現 {0} 可清理垃圾與 {1} 個高影響啟動項",
    "home.status.tight.detail": "系統碟剩餘空間不足 10%，建議立即清理",
    "home.status.lastscan": "上次掃描：{0}", "home.noscan": "還沒有掃描過", "home.noscan.detail": "還沒有掃描過，點擊「立即掃描」開始",
    "home.card.junk": "可清理垃圾", "home.card.junk.note": "點擊掃描查看可釋放空間", "home.card.junk.lastscan": "上次掃描 {0}",
    "home.card.startup": "啟動項", "home.card.startup.note": "個啟動項隨開機執行", "home.card.startup.note.high": "高影響啟動項，可能拖慢開機",
    "home.card.large": "大檔案", "home.card.large.note": "點擊分析查找", "home.card.large.analyzed": "已分析",
    "home.card.large.analyzed.note": "點擊查看大檔案詳情", "home.card.large.pending": "待分析",
    "home.card.apps": "已裝應用", "home.card.apps.note": "點擊管理已裝應用",
    "home.disk.title": "磁碟空間 (C:)", "home.disk.title.disk": "磁碟空間 ({0})", "home.disk.total": "總容量 —",
    "home.disk.used": "已使用 —", "home.disk.free": "可用 —", "home.disk.total.f": "總容量 {0}",
    "home.disk.used.f": "已使用 {0} ({1:F1}%)", "home.disk.free.f": "可用 {0} ({1:F1}%)", "home.disk.more": "查看空間去哪了 →",
    "home.space.title": "空間分析", "home.space.empty": "還沒有分析過這塊磁碟",
    "home.activity.title": "最近活動", "home.activity.empty": "還沒有活動記錄，掃描清理一下試試",
    "home.suggest.title": "智慧建議", "home.suggest.empty": "一切正常，沒有需要處理的建議",
    "home.suggest.note.safe": "可安全清理，不影響系統使用", "home.suggest.clean": "立即清理", "home.suggest.optimize": "去最佳化",
    "home.suggest.startup.title": "開機啟動建議", "home.suggest.startup.note": "發現 {0} 個高影響啟動項，建議最佳化",
    "home.hero.note": "讓電腦更乾淨&#x0a;執行更流暢！",
    "scan.start": "開始掃描", "scan.cover": "一次掃描涵蓋：系統垃圾 · 瀏覽器快取 · 應用快取 · 資源回收筒",
    "scan.privacy": "掃描全程在本機進行；預設只勾選安全項目，高風險項目永遠不會被自動選中。",
    "scan.preparing": "準備掃描…", "scan.found": "已發現 —", "scan.done": "掃描完成", "scan.reselectall": "全選安全項",
    "scan.group.safe": "可以安全清理", "scan.group.safe.note": "這些是系統與應用產生的暫存資料，清理無風險",
    "scan.group.cache": "瀏覽器與應用快取", "scan.group.cache.note": "快取類資料，應用會在需要時重新下載",
    "scan.group.check": "建議檢查", "scan.group.check.note": "清理前請確認這些內容不再需要",
    "result.title.found": "掃描完成，發現可釋放 {0}", "result.title.clean": "掃描完成，很乾淨！",
    "result.sub": "{0} · 共掃描 {1} 類項目",
    "row.files": "{0} 個檔案", "row.restore": "可進隔離區還原", "row.direct": "直接刪除",
    "row.running": "{0} 個相關程序執行中", "row.impact.tip": "清理影響：{0}",
    "clean.title": "正在清理…", "clean.freed": "已釋放 —",
    "done.title": "清理完成", "done.cancelled": "清理已中斷", "done.partial": "清理完成（部分跳過）",
    "done.freed.total": "共釋放 {0}", "done.note.quarantine": "隔離區檔案保留 {0} 天，可隨時在工具箱中還原。",
    "done.note.skip": "跳過的檔案正在被其他程式使用，關閉相關程式後下次清理即可移除。",
    "done.stat.ok": "清理成功", "done.stat.quar": "進入隔離區", "done.stat.skip": "跳過（佔用中）", "done.stat.fail": "失敗",
    "clean.tab.system": "系統垃圾", "clean.tab.app": "應用快取", "clean.tab.browser": "瀏覽器清理",
    "clean.tab.privacy": "隱私痕跡", "clean.tab.recycle": "資源回收筒",
    "clean.tabnote.0": "系統與應用產生的暫存檔、日誌與當機報告，預設只勾選安全項目",
    "clean.tabnote.1": "通訊與辦公軟體的快取和日誌，不會觸碰聊天記錄與文件",
    "clean.tabnote.2": "瀏覽器為加速上網產生的快取，不影響登入狀態、密碼與歷史",
    "clean.tabnote.3": "涉及個人記錄，預設全部不勾選，請仔細確認影響後再清理",
    "clean.tabnote.4": "清空資源回收筒前請確認裡面的檔案不再需要",
    "clean.privacy.banner": "隱私項預設全部不勾選。勾選前請閱讀每項的影響說明：清理 Cookie 會使網站登出，清理歷史記錄後不可復原。",
    "clean.privacy.warn": "隱私項清理後無法復原，請確認已了解各項影響。",
    "clean.recycle.desc": "清空後資源回收筒中的檔案將被永久刪除、無法復原。也可以先開啟資源回收筒檢查一遍。",
    "clean.empty.before": "點擊右上角「掃描」開始檢查這一類項目", "clean.empty.clean": "這一類很乾淨，沒有發現可清理的項目",
    "clean.empty.group": "點擊下方「掃描此分類」開始檢查這一類項目",
    "recycle.info": "{0} 個項目，共佔用 {1}", "recycle.empty": "資源回收筒是空的",
    "recycle.confirm.title": "清空資源回收筒？", "recycle.confirm.msg": "資源回收筒中的 {0} 個檔案（共 {1}）將被永久刪除，無法復原。",
    "toast.cleandone": "清理完成，釋放 {0}", "toast.skipped": "（跳過 {0} 項）", "toast.binemptied": "資源回收筒已清空",
    "toast.failed": "操作失敗",
    "dlg.clean.selected.title": "確認清理所選項目？", "dlg.clean.amount": "即將清理 {0} 的資料。",
    "dlg.clean.nrules": "即將清理 {0} 類項目，共 {1}。", "dlg.clean.confirmitems": "包含需要確認的項目：",
    "dlg.clean.quarantinehint": "可復原類檔案將進入隔離區。",
    "dlg.quickclean.title": "清理{0}？", "dlg.quickclean.msg": "預計可釋放 {0}。\n可復原類檔案會進入隔離區。",
    "space.tab.overview": "概覽", "space.tab.large": "大檔案", "space.tree.title": "資料夾佔用排行",
    "space.tree.hint": "點擊展開子資料夾；已跳過系統連結與無權限目錄",
    "space.empty": "還沒有分析過這塊磁碟，點擊右上角「開始分析」（掃描期間可隨時取消）",
    "space.scanning": "正在分析磁碟…", "space.cancelled": "已取消分析", "space.failed": "分析失敗：",
    "space.done": "分析完成，用時 {0:F0} 秒", "space.rendererror": "分析結果渲染異常，詳情見日誌",
    "space.scanned": "已掃描 {0:N0} 個檔案", "space.total": "共 {0}",
    "space.used.f": "已使用 {0} / {1}（{2:F1}%），可用 {3}", "space.used.f2": "已使用 {0} / {1}，可用 {2}",
    "space.analyzed.f": "分析於 {0} · {1:N0} 個檔案 · {2:F0} 秒", "space.lastanalysis": "上次分析：{0}",
    "space.notanalyzed": "這塊磁碟還沒有分析過", "space.large.filter": "大小篩選",
    "space.large.none": "沒有找到大於 {0:F0} MB 的檔案", "space.modified": "修改於", "space.file": "檔案",
    "space.recycle.title": "移至資源回收筒？", "space.recycle.msg": "{0}（{1}）將移至資源回收筒，可隨時還原。",
    "toast.whitelisted": "已加入白名單，掃描與清理將跳過該檔案", "toast.largecleaned": "清理了大檔案 {0}",
    "toast.recycled": "已移至資源回收筒，釋放 {0}", "toast.recyclefailed": "移至資源回收筒失敗，檔案可能被佔用",
    "startup.desc": "關閉啟動項後應用仍可手動開啟；所有修改都會記錄原狀態，可隨時還原。",
    "startup.col.toggle": "狀態", "startup.col.impact": "啟動影響", "startup.col.source": "來源", "startup.col.suggest": "建議",
    "startup.loading": "正在讀取啟動項…", "startup.empty": "沒有符合的啟動項", "startup.systemchip": "系統元件",
    "startup.src.reghkcu": "登錄檔 (目前使用者)", "startup.src.reghklm": "登錄檔 (本機)",
    "startup.src.folderuser": "啟動資料夾 (使用者)", "startup.src.foldercommon": "啟動資料夾 (公用)",
    "startup.src.task": "排程工作", "startup.impact.high": "高", "startup.impact.med": "中",
    "startup.impact.low": "低", "startup.impact.unknown": "未測量",
    "startup.suggest.off": "可考慮關閉", "startup.suggest.system": "系統元件", "startup.suggest.keep": "保留",
    "startup.enabled": "已啟用", "startup.disabled": "已停用", "startup.toggled": "{0}啟動項「{1}」",
    "apps.desc": "解除安裝將呼叫應用程式自帶的解除安裝程式；完成後可掃描確認的殘留檔案（進入隔離區，可還原）。",
    "apps.sort.name": "按名稱", "apps.sort.size": "按大小", "apps.sort.date": "按安裝日期",
    "apps.col.name": "應用程式", "apps.col.publisher": "發佈者", "apps.col.size": "大小", "apps.col.date": "安裝日期",
    "apps.loading": "正在讀取已安裝應用…", "apps.empty": "沒有符合的應用", "apps.store": "Microsoft Store 應用",
    "apps.unknown": "未知", "apps.uninstall.title": "解除安裝 {0}？", "apps.uninstall.start": "開始解除安裝",
    "apps.uninstall.msg": "應用程式大小：{0}\n\n將啟動應用程式自帶的解除安裝程式，請在解除安裝精靈中完成操作。",
    "apps.waiting": "等待「{0}」解除安裝完成…\n完成解除安裝精靈後會自動繼續", "apps.notdetected": "未偵測到解除安裝完成，可能已取消",
    "apps.uninstalled.toast": "「{0}」已解除安裝", "apps.uninstalled.log": "解除安裝了應用「{0}」", "apps.uninstall.failed": "無法啟動解除安裝程式：",
    "leftover.title": "發現可能的殘留", "leftover.title.f": "「{0}」的解除安裝殘留",
    "leftover.desc": "以下是可確認屬於該應用的資料目錄與設定鍵。勾選後進入隔離區（可隨時還原）。",
    "leftover.skip": "不清理，完成", "leftover.clean": "清理勾選項", "leftover.reg": "登錄檔設定鍵（匯出備份後刪除）",
    "leftover.datadir": "資料目錄", "leftover.installdir": "安裝目錄",
    "tool.desc": "檔案粉碎不會進入資源回收筒；隔離區檔案可隨時還原；重複檔案基於內容雜湊檢測。",
    "tool.quarantine.title": "清理隔離區", "tool.quar.empty": "隔離區是空的",
    "tool.quar.summary": "{0} 個項目，共 {1}；超過 {2} 天將自動永久刪除",
    "tool.quar.daysleft": "剩 {0} 天", "tool.purge.title": "清空隔離區？",
    "tool.purge.msg": "隔離區中的 {0} 個項目將被永久刪除，無法復原。",
    "tool.shred.title": "檔案粉碎", "tool.shred.desc": "從檔案系統中永久刪除檔案，使其不進入資源回收筒。注意：對 SSD 無法保證底層快閃記憶體資料立即實體覆寫。此操作不可復原，請謹慎選擇檔案。",
    "tool.shred.confirm.title": "確認粉碎？", "tool.shred.confirm.msg": "{0}\n\n{1} 將被覆寫後永久刪除，不進入資源回收筒，無法透過復原軟體輕易還原。\n\n此操作不可復原！",
    "tool.shred.log": "粉碎了{0}「{1}」", "tool.folder": "資料夾", "tool.file": "檔案",
    "tool.dup.title": "重複檔案", "tool.dup.desc": "透過內容雜湊確認重複（不是只看檔名）。掃描範圍預設為圖片、影片與下載目錄。",
    "tool.dup.none": "沒有發現重複檔案", "tool.dup.summary": "{0} 組重複檔案，可釋放 {1}",
    "tool.dup.progress": "已掃描 {0:N0} 個檔案…", "tool.dup.more": "… 還有 {0} 組未顯示",
    "tool.dup.group": "{0} 個相同檔案 · 每個 {1} · 可釋放 {2}", "tool.dup.tip": "勾選 = 刪除這份副本",
    "tool.dup.clean.title": "刪除選中的副本？", "tool.dup.clean.msg": "共 {0} 個檔案，{1}，將移至資源回收筒（可還原）。",
    "tool.history.title": "清理歷史", "tool.win.title": "Windows 快捷工具", "tool.win.desc": "直達系統自帶工具，安全無風險",
    "tool.win.taskmgr": "工作管理員", "tool.win.taskmgr.d": "查看處理程序與效能",
    "tool.win.storage": "儲存設定", "tool.win.storage.d": "管理儲存空間",
    "tool.win.diskmgmt": "磁碟管理", "tool.win.diskmgmt.d": "管理分割區與磁碟",
    "tool.win.devmgmt": "裝置管理員", "tool.win.devmgmt.d": "管理硬體驅動",
    "tool.win.control": "控制台", "tool.win.control.d": "系統經典設定",
    "tool.win.msinfo": "系統資訊", "tool.win.msinfo.d": "查看系統設定",
    "tool.win.update": "Windows Update", "tool.win.update.d": "檢查系統更新",
    "tool.win.restore": "系統還原", "tool.win.restore.d": "建立或使用還原點",
    "history.empty": "還沒有活動記錄", "history.clear.title": "清空歷史？", "history.clear.msg": "所有清理與操作記錄將被刪除。",
    "history.type.clean": "清理", "history.type.autoclean": "自動清理", "history.type.restore": "還原",
    "history.type.uninstall": "解除安裝", "history.type.startup": "啟動項", "history.type.quarantine": "隔離區",
    "history.type.shred": "粉碎", "history.type.other": "其他",
    "settings.title": "設定", "settings.sec.general": "一般", "settings.sec.exclude": "排除目錄與白名單",
    "settings.sec.notify": "通知", "settings.sec.advanced": "進階", "settings.sec.privacy": "隱私", "settings.sec.about": "關於",
    "settings.exc.desc": "這些目錄與檔案在所有掃描和清理中都會被跳過。", "settings.exc.empty": "暫無排除目錄與白名單",
    "settings.whitelist": "白名單", "settings.excluded": "排除",
    "settings.btn.addexclude": "新增排除目錄", "settings.btn.addwhitelist": "新增白名單檔案/目錄",
    "settings.pick.whitelist": "選擇要加入白名單的檔案", "settings.pick.exclude": "選擇要在掃描清理中排除的目錄",
    "settings.days": "天", "settings.threads": "執行緒",
    "settings.theme.light": "淺色", "settings.theme.dark": "深色", "settings.theme.system": "跟隨系統",
    "settings.freq.daily": "每天", "settings.freq.weekly": "每週", "settings.freq.monthly": "每月",
    "settings.lang.auto": "跟隨系統語言",
    "settings.row.language": "介面語言", "settings.row.language.d": "切換後立即生效",
    "settings.row.autostart": "開機自動執行清理優化大師", "settings.row.autostart.d": "開機後只在背景常駐，不執行任何操作",
    "settings.row.mintotray": "最小化到系統列", "settings.row.mintotray.d": "點擊最小化按鈕時隱藏到系統列",
    "settings.row.closetotray": "關閉按鈕最小化到系統列", "settings.row.closetotray.d": "點擊關閉按鈕時詢問並最小化，而非結束",
    "settings.row.theme": "主題",
    "settings.row.quarantine": "清理後進入隔離區", "settings.row.quarantine.d": "非快取類檔案先進入隔離區，可隨時還原（建議開啟）",
    "settings.row.quarantine.days": "隔離區保留時間", "settings.row.quarantine.days.d": "到期後自動永久刪除",
    "settings.row.autoclean": "自動清理", "settings.row.autoclean.d": "按排程自動清理暫存檔與快取等安全項目",
    "settings.row.autoclean.freq": "自動清理頻率", "settings.row.autoclean.freq.d": "應用程式執行期間在背景執行",
    "settings.row.notifydisk": "磁碟空間不足提醒", "settings.row.notifydisk.d": "系統碟剩餘不足 10% 時提醒（低頻，不打擾）",
    "settings.row.notifyauto": "自動清理結果通知", "settings.row.notifyweekly": "每週空間報告",
    "settings.row.notifynews": "產品訊息", "settings.row.notifynews.d": "新功能與活動通知，預設關閉",
    "settings.row.threads": "掃描執行緒數", "settings.row.threads.d": "執行緒越多掃描越快，但機械硬碟建議調低",
    "settings.row.hidden": "掃描隱藏檔案", "settings.row.junction": "跟隨目錄連結 (Junction)",
    "settings.row.junction.d": "跟隨符號連結掃描可能造成重複統計，預設關閉",
    "settings.row.stats": "匿名使用統計", "settings.row.stats.d": "僅上報功能使用次數與錯誤碼，不含任何檔案資訊；目前版本完全不上傳資料",
    "settings.row.crash": "當機報告",
    "settings.privacy.desc": "掃描資料全部保存在本機。本應用不收集、不上傳任何檔名、路徑與內容。",
    "settings.about.slogan": "清得明白，優化得安心。", "settings.about.support": "支援與意見回饋",
    "settings.about.site": "支援網站", "settings.about.email": "聯絡郵箱", "settings.about.repo": "開源倉庫",
    "settings.about.wechat": "微信掃碼或搜尋「AI虚拟助理」，取得使用技巧與更新動態。",
    "wizard.welcome": "歡迎使用清理優化大師",
    "wizard.slogan": "清得明白，優化得安心。\n我們只做可解釋、可預覽、可還原的清理，不搞虛假加速。",
    "wizard.privacy.title": "隱私承諾",
    "wizard.privacy.items": "· 所有掃描結果、檔名、路徑都只保存在你的電腦本機。\n· 預設不開啟任何資料上報，也不上傳任何檔案內容。\n· 關鍵清理項進入隔離區，7~30 天內可隨時還原。\n· 刪除前永遠先預覽，絕不靜默刪除你的檔案。",
    "wizard.auto.title": "開啟自動清理？", "wizard.auto.desc": "僅自動清理系統暫存檔與應用快取等安全項目，每週一次。",
    "wizard.auto.yes": "開啟自動清理", "wizard.auto.no": "暫不開啟", "wizard.next": "開始體驗", "wizard.next2": "下一步",
    "tray.open": "開啟清理優化大師", "tray.quickscan": "快速掃描", "tray.exit": "結束",
    "tray.autoclean": "自動清理：", "tray.on": "開", "tray.off": "關",
    "dlg.exit.title": "結束清理優化大師？", "dlg.exit.msg": "結束後將不再提供自動清理與磁碟空間監控。",
    "toast.traymin": "已最小化到系統列，右鍵系統列圖示可結束",
    "toast.scanstopped": "已停止掃描", "toast.scanfailed": "掃描失敗：", "toast.noselect": "請先勾選要清理的項目",
    "toast.cleancancelled": "清理已取消", "toast.cleanfailed": "清理失敗：", "toast.nothing": "沒有發現可清理的內容",
    "toast.cleaned": "已清理，釋放了 {0}", "toast.readfailed": "讀取失敗：", "toast.langapplied": "介面語言已切換",
}
