# -*- coding: utf-8 -*-
"""Français / Español / Deutsch (UI ; les longues descriptions de règles retombent sur en-US)."""

FR = {
    "common.selected": "Sélectionné", "common.freeable": "récupérable", "common.viewall": "Tout voir",
    "common.loading": "Chargement…", "common.scanning": "Analyse…", "common.n.items": "{0} éléments",
    "common.approx": "~", "btn.cancel": "Annuler", "btn.exit": "Quitter", "btn.refresh": "Actualiser",
    "btn.stopscan": "Arrêter l'analyse", "btn.rescan": "Réanalyser", "btn.restore": "Restaurer", "btn.deleteperm": "Supprimer définitivement",
    "btn.uninstall": "Désinstaller", "btn.recycle": "Mettre à la corbeille", "btn.remove": "Retirer", "btn.analyze.start": "Analyser",
    "btn.scan.now": "Analyser maintenant", "btn.more": "Plus d'outils", "btn.clean.selected": "Nettoyer la sélection",
    "btn.clean.start": "Commencer le nettoyage", "btn.done.home": "Retour à l'accueil", "btn.done.quarantine": "Ouvrir la quarantaine",
    "btn.emptybin": "Vider la corbeille", "btn.openbin": "Ouvrir la corbeille", "btn.scangroup": "Analyser ce groupe",
    "btn.cleansel": "Nettoyer la sélection", "btn.dupscan": "Lancer l'analyse", "btn.dup.rescan": "Réanalyser",
    "btn.dupkeepnew": "Garder les plus récents", "btn.dupclean": "Mettre la sélection à la corbeille",
    "btn.clearhistory": "Effacer l'historique", "btn.clearlocal": "Effacer l'historique local", "btn.purge": "Vider la quarantaine",
    "btn.shredfile": "Broyer des fichiers…", "btn.shreddir": "Broyer un dossier…", "btn.shred": "Broyer définitivement",
    "tip.min": "Réduire", "tip.max": "Agrandir", "tip.close": "Fermer",
    "nav.home": "Accueil", "nav.scan": "Analyse intelligente", "nav.clean": "Nettoyage", "nav.space": "Analyse du disque",
    "nav.startup": "Démarrage", "nav.apps": "Applications", "nav.toolbox": "Boîte à outils", "nav.settings": "Paramètres",
    "risk.safe": "Sûr", "risk.low": "Risque faible", "risk.confirm": "À vérifier", "risk.high": "Risque élevé",
    "cat.system": "Système", "cat.apps": "Applications", "cat.images": "Images", "cat.videos": "Vidéos",
    "cat.audio": "Audio", "cat.documents": "Documents", "cat.archives": "Archives", "cat.other": "Autres",
    "time.now": "À l'instant", "time.minago": "il y a {0} min", "time.today": "Aujourd'hui {0}", "time.yesterday": "Hier {0}",
    "home.slogan": "Des analyses régulières gardent votre PC au top",
    "home.status.good": "Votre PC est en bon état", "home.status.suggest": "Un nettoyage est recommandé", "home.status.tight": "Espace disque faible",
    "home.status.suggest.detail": "{0} de fichiers inutiles et {1} éléments de démarrage à fort impact trouvés",
    "home.status.tight.detail": "Moins de 10 % d'espace libre sur le disque système — nettoyez maintenant",
    "home.status.lastscan": "Dernière analyse : {0}", "home.noscan": "Pas encore analysé", "home.noscan.detail": "Cliquez sur « Analyser maintenant » pour commencer",
    "home.card.junk": "Fichiers inutiles", "home.card.junk.note": "Analyser pour voir l'espace récupérable", "home.card.junk.lastscan": "Dernière analyse {0}",
    "home.card.startup": "Démarrage", "home.card.startup.note": "éléments lancés au démarrage", "home.card.startup.note.high": "éléments à fort impact susceptibles de ralentir le démarrage",
    "home.card.large": "Gros fichiers", "home.card.large.note": "Analyser pour trouver", "home.card.large.analyzed": "Analysé",
    "home.card.large.analyzed.note": "Cliquer pour voir les détails", "home.card.large.pending": "En attente",
    "home.card.apps": "Applications", "home.card.apps.note": "Cliquer pour gérer",
    "home.disk.title": "Disque (C:)", "home.disk.title.disk": "Disque ({0})", "home.disk.total": "Total —",
    "home.disk.used": "Utilisé —", "home.disk.free": "Libre —", "home.disk.total.f": "Total {0}",
    "home.disk.used.f": "Utilisé {0} ({1:F1} %)", "home.disk.free.f": "Libre {0} ({1:F1} %)", "home.disk.more": "Où passe mon espace →",
    "home.space.title": "Analyse du disque", "home.space.empty": "Ce disque n'a pas encore été analysé",
    "home.activity.title": "Activité récente", "home.activity.empty": "Aucune activité — lancez une analyse",
    "home.suggest.title": "Suggestions", "home.suggest.empty": "Tout est bon — rien à signaler",
    "home.suggest.note.safe": "Nettoyage sûr, sans impact sur le système", "home.suggest.clean": "Nettoyer", "home.suggest.optimize": "Optimiser",
    "home.suggest.startup.title": "Suggestion de démarrage", "home.suggest.startup.note": "{0} éléments à fort impact — à optimiser",
    "home.hero.note": "Un PC plus propre,\nplus fluide !",
    "scan.start": "Lancer l'analyse", "scan.cover": "Une seule analyse : fichiers système · caches navigateurs · caches d'applications · corbeille",
    "scan.privacy": "Tout s'exécute en local ; seuls les éléments sûrs sont pré-cochés, les éléments risqués ne le sont jamais.",
    "scan.preparing": "Préparation…", "scan.found": "Trouvé —", "scan.done": "Analyse terminée", "scan.reselectall": "Sélectionner les éléments sûrs",
    "scan.group.safe": "Nettoyage sûr", "scan.group.safe.note": "Données temporaires du système et des applications — sans risque",
    "scan.group.cache": "Caches navigateurs & apps", "scan.group.cache.note": "Données de cache ; les applications les retéléchargent",
    "scan.group.check": "À vérifier", "scan.group.check.note": "Confirmez que ces contenus ne sont plus nécessaires",
    "result.title.found": "Analyse terminée — {0} récupérables", "result.title.clean": "Analyse terminée — tout est propre !",
    "result.sub": "{0} · {1} catégories analysées",
    "row.files": "{0} fichiers", "row.restore": "restaurable via la quarantaine", "row.direct": "supprimé directement",
    "row.running": "{0} processus en cours d'exécution", "row.impact.tip": "Impact : {0}",
    "clean.title": "Nettoyage…", "clean.freed": "Libéré —",
    "done.title": "Nettoyage terminé", "done.cancelled": "Nettoyage interrompu", "done.partial": "Nettoyage terminé (certains ignorés)",
    "done.freed.total": "{0} libérés au total", "done.note.quarantine": "Les fichiers en quarantaine sont conservés {0} jours, restaurables depuis la boîte à outils.",
    "done.note.skip": "Les fichiers ignorés sont utilisés par d'autres programmes ; fermez-les et réessayez plus tard.",
    "done.stat.ok": "Nettoyés", "done.stat.quar": "En quarantaine", "done.stat.skip": "Ignorés (utilisés)", "done.stat.fail": "Échecs",
    "clean.tab.system": "Fichiers système", "clean.tab.app": "Caches d'apps", "clean.tab.browser": "Navigateurs",
    "clean.tab.privacy": "Traces de confidentialité", "clean.tab.recycle": "Corbeille",
    "clean.tabnote.0": "Fichiers temporaires, journaux et rapports de plantage — seuls les éléments sûrs sont pré-cochés",
    "clean.tabnote.1": "Caches et journaux des applications de messagerie et bureautiques — vos conversations et documents ne sont jamais touchés",
    "clean.tabnote.2": "Caches d'accélération des navigateurs — connexions, mots de passe et historique inchangés",
    "clean.tabnote.3": "Données personnelles — toutes décochées par défaut ; lisez attentivement chaque impact",
    "clean.tabnote.4": "Vérifiez que la corbeille ne contient rien d'utile avant de la vider",
    "clean.privacy.banner": "Les éléments de confidentialité sont décochés par défaut. Lisez chaque impact : effacer les cookies déconnecte les sites ; l'historique effacé est irrécupérable.",
    "clean.privacy.warn": "Les éléments de confidentialité ne peuvent pas être restaurés après nettoyage.",
    "clean.recycle.desc": "Vider la corbeille supprime définitivement son contenu. Vous pouvez d'abord l'ouvrir pour vérifier.",
    "clean.empty.before": "Cliquez sur « Analyser ce groupe » ci-dessous", "clean.empty.clean": "Cette catégorie est déjà propre",
    "clean.empty.group": "Cliquez sur « Analyser ce groupe » ci-dessous",
    "recycle.info": "{0} éléments, {1}", "recycle.empty": "La corbeille est vide",
    "recycle.confirm.title": "Vider la corbeille ?", "recycle.confirm.msg": "{0} fichiers ({1}) seront définitivement supprimés. Irréversible.",
    "toast.cleandone": "Nettoyage terminé — {0} libérés", "toast.skipped": " ({0} ignorés)", "toast.binemptied": "Corbeille vidée",
    "toast.failed": "Échec de l'opération",
    "dlg.clean.selected.title": "Nettoyer les éléments sélectionnés ?", "dlg.clean.amount": "Sur le point de nettoyer {0}.",
    "dlg.clean.nrules": "Nettoyage de {0} catégories, {1} au total.", "dlg.clean.confirmitems": "Éléments à vérifier :",
    "dlg.clean.quarantinehint": "Les fichiers restaurables seront mis en quarantaine.",
    "dlg.quickclean.title": "Nettoyer {0} ?", "dlg.quickclean.msg": "Environ {0} seront libérés.\nLes fichiers restaurables vont en quarantaine.",
    "space.tab.overview": "Aperçu", "space.tab.large": "Gros fichiers", "space.tree.title": "Classement des dossiers",
    "space.tree.hint": "Cliquez pour déplier ; liens système et dossiers inaccessibles ignorés",
    "space.empty": "Ce disque n'a pas encore été analysé. Cliquez sur « Analyser » ci-dessus (annulable à tout moment)",
    "space.scanning": "Analyse du disque…", "space.cancelled": "Analyse annulée", "space.failed": "Échec de l'analyse : ",
    "space.done": "Analyse terminée en {0:F0} s", "space.rendererror": "Erreur d'affichage des résultats — voir le journal",
    "space.scanned": "{0:N0} fichiers analysés", "space.total": "total {0}",
    "space.used.f": "Utilisé {0} / {1} ({2:F1} %), libre {3}", "space.used.f2": "Utilisé {0} / {1}, libre {2}",
    "space.analyzed.f": "Analysé {0} · {1:N0} fichiers · {2:F0} s", "space.lastanalysis": "Dernière analyse : {0}",
    "space.notanalyzed": "Ce disque n'a pas encore été analysé", "space.large.filter": "Filtre de taille",
    "space.large.none": "Aucun fichier de plus de {0:F0} Mo trouvé", "space.modified": "Modifié", "space.file": "FICHIER",
    "space.recycle.title": "Mettre à la corbeille ?", "space.recycle.msg": "{0} ({1}) sera mis à la corbeille. Restaurable à tout moment.",
    "toast.whitelisted": "Ajouté à la liste blanche — ce fichier sera ignoré", "toast.largecleaned": "Gros fichier nettoyé {0}",
    "toast.recycled": "Mis à la corbeille — {0} libérés", "toast.recyclefailed": "Échec : le fichier est peut-être en cours d'utilisation",
    "startup.desc": "Les applications désactivées restent ouvrables manuellement ; chaque modification est réversible.",
    "startup.col.toggle": "État", "startup.col.impact": "Impact", "startup.col.source": "Source", "startup.col.suggest": "Conseil",
    "startup.loading": "Chargement des éléments de démarrage…", "startup.empty": "Aucun élément correspondant", "startup.systemchip": "Composant système",
    "startup.src.reghkcu": "Registre (utilisateur)", "startup.src.reghklm": "Registre (machine)",
    "startup.src.folderuser": "Dossier Démarrage (utilisateur)", "startup.src.foldercommon": "Dossier Démarrage (tous)",
    "startup.src.task": "Tâche planifiée", "startup.impact.high": "Élevé", "startup.impact.med": "Moyen",
    "startup.impact.low": "Faible", "startup.impact.unknown": "Non mesuré",
    "startup.suggest.off": "À désactiver éventuellement", "startup.suggest.system": "Composant système", "startup.suggest.keep": "Garder",
    "startup.enabled": "Activé", "startup.disabled": "Désactivé", "startup.toggled": "{0} l'élément de démarrage « {1} »",
    "apps.desc": "La désinstallation lance le programme de l'application ; ensuite, les résidus confirmés peuvent être nettoyés (en quarantaine, restaurables).",
    "apps.sort.name": "Par nom", "apps.sort.size": "Par taille", "apps.sort.date": "Par date d'installation",
    "apps.col.name": "Application", "apps.col.publisher": "Éditeur", "apps.col.size": "Taille", "apps.col.date": "Installé le",
    "apps.loading": "Chargement des applications…", "apps.empty": "Aucune application correspondante", "apps.store": "Application Microsoft Store",
    "apps.unknown": "Inconnue", "apps.uninstall.title": "Désinstaller {0} ?", "apps.uninstall.start": "Désinstaller",
    "apps.uninstall.msg": "Taille : {0}\n\nLe désinstalleur de l'application va se lancer — suivez son assistant.",
    "apps.waiting": "En attente de la désinstallation de « {0} »…\nReprise automatique une fois terminée",
    "apps.notdetected": "Désinstallation non détectée — elle a peut-être été annulée",
    "apps.uninstalled.toast": "« {0} » a été désinstallé", "apps.uninstalled.log": "Application désinstallée « {0} »",
    "apps.uninstall.failed": "Impossible de lancer le désinstalleur : ",
    "leftover.title": "Résidus possibles trouvés", "leftover.title.f": "Résidus de « {0} »",
    "leftover.desc": "Dossiers de données et clés de registre appartenant à cette application. Les éléments cochés partent en quarantaine (restaurables).",
    "leftover.skip": "Ignorer, terminer", "leftover.clean": "Nettoyer la sélection", "leftover.reg": "Clé de registre (sauvegardée puis supprimée)",
    "leftover.datadir": "Dossier de données", "leftover.installdir": "Dossier d'installation",
    "tool.desc": "Les fichiers broyés ne passent pas par la corbeille ; les fichiers en quarantaine sont restaurables ; les doublons sont détectés par empreinte de contenu.",
    "tool.quarantine.title": "Quarantaine", "tool.quar.empty": "La quarantaine est vide",
    "tool.quar.summary": "{0} éléments, {1} ; suppression automatique après {2} jours",
    "tool.quar.daysleft": "{0} jours restants", "tool.purge.title": "Vider la quarantaine ?",
    "tool.purge.msg": "{0} éléments en quarantaine seront définitivement supprimés. Irréversible.",
    "tool.shred.title": "Broyeur de fichiers", "tool.shred.desc": "Supprime définitivement les fichiers sans passer par la corbeille. NB : sur SSD, un écrasement physique immédiat ne peut être garanti. Irréversible — choisissez avec soin.",
    "tool.shred.confirm.title": "Broyer cet élément ?", "tool.shred.confirm.msg": "{0}\n\n{1} sera écrasé puis définitivement supprimé — sans passage par la corbeille.\n\nIrréversible !",
    "tool.shred.log": "{0} « {1} » broyé", "tool.folder": "dossier", "tool.file": "fichier",
    "tool.dup.title": "Fichiers en double", "tool.dup.desc": "Les doublons sont confirmés par empreinte du contenu (jamais par nom). Portée par défaut : Images, Vidéos et Téléchargements.",
    "tool.dup.none": "Aucun doublon trouvé", "tool.dup.summary": "{0} groupes de doublons, {1} récupérables",
    "tool.dup.progress": "{0:N0} fichiers analysés…", "tool.dup.more": "… {0} groupes supplémentaires non affichés",
    "tool.dup.group": "{0} fichiers identiques · {1} chacun · {2} récupérables", "tool.dup.tip": "Coché = supprimer cette copie",
    "tool.dup.clean.title": "Supprimer les copies sélectionnées ?", "tool.dup.clean.msg": "{0} fichiers ({1}) seront mis à la corbeille (restaurables).",
    "tool.history.title": "Historique", "tool.win.title": "Outils Windows", "tool.win.desc": "Raccourcis vers les outils système intégrés — sans risque",
    "tool.win.taskmgr": "Gestionnaire des tâches", "tool.win.taskmgr.d": "Processus et performances",
    "tool.win.storage": "Stockage", "tool.win.storage.d": "Gérer l'espace de stockage",
    "tool.win.diskmgmt": "Gestion des disques", "tool.win.diskmgmt.d": "Gérer partitions et disques",
    "tool.win.devmgmt": "Gestionnaire de périphériques", "tool.win.devmgmt.d": "Matériel et pilotes",
    "tool.win.control": "Panneau de configuration", "tool.win.control.d": "Paramètres classiques",
    "tool.win.msinfo": "Informations système", "tool.win.msinfo.d": "Configuration du système",
    "tool.win.update": "Windows Update", "tool.win.update.d": "Rechercher les mises à jour",
    "tool.win.restore": "Restauration du système", "tool.win.restore.d": "Créer ou utiliser des points de restauration",
    "history.empty": "Aucune activité", "history.clear.title": "Effacer l'historique ?", "history.clear.msg": "Tous les enregistrements seront supprimés.",
    "history.type.clean": "Nettoyage", "history.type.autoclean": "Auto", "history.type.restore": "Restauration",
    "history.type.uninstall": "Désinstallation", "history.type.startup": "Démarrage", "history.type.quarantine": "Quarantaine",
    "history.type.shred": "Broyage", "history.type.other": "Autre",
    "settings.title": "Paramètres", "settings.sec.general": "Général", "settings.sec.exclude": "Exclusions & liste blanche",
    "settings.sec.notify": "Notifications", "settings.sec.advanced": "Avancé", "settings.sec.privacy": "Confidentialité", "settings.sec.about": "À propos",
    "settings.exc.desc": "Ces dossiers et fichiers sont ignorés par toutes les analyses et nettoyages.", "settings.exc.empty": "Aucune exclusion ni entrée de liste blanche",
    "settings.whitelist": "Liste blanche", "settings.excluded": "Exclu",
    "settings.btn.addexclude": "Ajouter un dossier exclu", "settings.btn.addwhitelist": "Ajouter à la liste blanche",
    "settings.pick.whitelist": "Choisir un fichier à mettre en liste blanche", "settings.pick.exclude": "Choisir un dossier à exclure",
    "settings.days": "jours", "settings.threads": "threads",
    "settings.theme.light": "Clair", "settings.theme.dark": "Sombre", "settings.theme.system": "Suivre le système",
    "settings.freq.daily": "Chaque jour", "settings.freq.weekly": "Chaque semaine", "settings.freq.monthly": "Chaque mois",
    "settings.lang.auto": "Langue du système",
    "settings.row.language": "Langue de l'interface", "settings.row.language.d": "Appliqué immédiatement",
    "settings.row.autostart": "Lancer au démarrage de Windows", "settings.row.autostart.d": "Attend silencieusement dans la zone de notification",
    "settings.row.mintotray": "Réduire vers la zone de notification", "settings.row.mintotray.d": "Le bouton réduire masque dans la zone de notification",
    "settings.row.closetotray": "Fermer = réduire", "settings.row.closetotray.d": "Le bouton fermer demande et réduit au lieu de quitter",
    "settings.row.theme": "Thème",
    "settings.row.quarantine": "Mettre en quarantaine", "settings.row.quarantine.d": "Les fichiers non-cache vont d'abord en quarantaine, restaurables (recommandé)",
    "settings.row.quarantine.days": "Conservation en quarantaine", "settings.row.quarantine.days.d": "Suppression automatique après expiration",
    "settings.row.autoclean": "Nettoyage automatique", "settings.row.autoclean.d": "Nettoie les éléments sûrs selon la planification",
    "settings.row.autoclean.freq": "Fréquence", "settings.row.autoclean.freq.d": "En arrière-plan pendant que l'application tourne",
    "settings.row.notifydisk": "Alerte d'espace disque faible", "settings.row.notifydisk.d": "Alerte sous 10 % de libre sur le disque système (rare)",
    "settings.row.notifyauto": "Résultats du nettoyage auto", "settings.row.notifyweekly": "Rapport hebdomadaire",
    "settings.row.notifynews": "Actualités produit", "settings.row.notifynews.d": "Nouveautés et événements, désactivé par défaut",
    "settings.row.threads": "Threads d'analyse", "settings.row.threads.d": "Plus de threads = plus rapide ; réduisez sur HDD",
    "settings.row.hidden": "Analyser les fichiers cachés", "settings.row.junction": "Suivre les liens de répertoires (Junctions)",
    "settings.row.junction.d": "Suivre les liens peut doubler les statistiques ; désactivé par défaut",
    "settings.row.stats": "Statistiques anonymes", "settings.row.stats.d": "Compteurs d'utilisation et codes d'erreur uniquement — cette version n'envoie rien",
    "settings.row.crash": "Rapports de plantage",
    "settings.privacy.desc": "Toutes les données d'analyse restent sur cet appareil. Aucun nom de fichier, chemin ou contenu n'est collecté ou envoyé.",
    "settings.about.slogan": "Nettoyer clairement, optimiser sereinement.", "settings.about.support": "Support & retours",
    "settings.about.site": "Site web", "settings.about.email": "E-mail", "settings.about.repo": "Code source",
    "settings.about.wechat": "Scannez ou cherchez « AI虚拟助理 » dans WeChat pour astuces et actualités.",
    "wizard.welcome": "Bienvenue dans CleanMaster",
    "wizard.slogan": "Nettoyer clairement, optimiser sereinement.\nNous ne faisons qu'un nettoyage explicable, prévisualisable et restaurable — sans fausses optimisations.",
    "wizard.privacy.title": "Notre engagement de confidentialité",
    "wizard.privacy.items": "· Tous les résultats d'analyse, noms de fichiers et chemins restent sur ce PC.\n· Aucune télémétrie par défaut ; aucun contenu de fichier n'est envoyé.\n· Les nettoyages importants vont en quarantaine — restaurables 7 à 30 jours.\n· Toujours prévisualisés avant suppression — jamais supprimés en silence.",
    "wizard.auto.title": "Activer le nettoyage automatique ?", "wizard.auto.desc": "Nettoie uniquement les éléments sûrs (fichiers temporaires, caches d'apps), une fois par semaine.",
    "wizard.auto.yes": "Activer", "wizard.auto.no": "Plus tard", "wizard.next": "Commencer", "wizard.next2": "Suivant",
    "tray.open": "Ouvrir CleanMaster", "tray.quickscan": "Analyse rapide", "tray.exit": "Quitter",
    "tray.autoclean": "Nettoyage auto : ", "tray.on": "activé", "tray.off": "désactivé",
    "dlg.exit.title": "Quitter CleanMaster ?", "dlg.exit.msg": "Le nettoyage automatique et la surveillance du disque s'arrêtent en quittant.",
    "toast.traymin": "Réduit dans la zone de notification — clic droit sur l'icône pour quitter",
    "toast.scanstopped": "Analyse arrêtée", "toast.scanfailed": "Échec de l'analyse : ", "toast.noselect": "Sélectionnez d'abord des éléments à nettoyer",
    "toast.cleancancelled": "Nettoyage annulé", "toast.cleanfailed": "Échec du nettoyage : ",
    "toast.nothing": "Rien à nettoyer", "toast.cleaned": "Nettoyé — {0} libérés",
    "toast.readfailed": "Échec du chargement : ", "toast.langapplied": "Langue de l'interface modifiée",
}

ES = {
    "common.selected": "Seleccionado", "common.freeable": "recuperable", "common.viewall": "Ver todo",
    "common.loading": "Cargando…", "common.scanning": "Escaneando…", "common.n.items": "{0} elementos",
    "common.approx": "~", "btn.cancel": "Cancelar", "btn.exit": "Salir", "btn.refresh": "Actualizar",
    "btn.stopscan": "Detener análisis", "btn.rescan": "Volver a analizar", "btn.restore": "Restaurar", "btn.deleteperm": "Eliminar definitivamente",
    "btn.uninstall": "Desinstalar", "btn.recycle": "Mover a la papelera", "btn.remove": "Quitar", "btn.analyze.start": "Analizar",
    "btn.scan.now": "Analizar ahora", "btn.more": "Más herramientas", "btn.clean.selected": "Limpiar selección",
    "btn.clean.start": "Iniciar limpieza", "btn.done.home": "Volver al inicio", "btn.done.quarantine": "Abrir cuarentena",
    "btn.emptybin": "Vaciar papelera", "btn.openbin": "Abrir papelera", "btn.scangroup": "Escanear grupo",
    "btn.cleansel": "Limpiar selección", "btn.dupscan": "Iniciar análisis", "btn.dup.rescan": "Volver a analizar",
    "btn.dupkeepnew": "Conservar el más reciente", "btn.dupclean": "Mover selección a la papelera",
    "btn.clearhistory": "Borrar historial", "btn.clearlocal": "Borrar historial local", "btn.purge": "Vaciar cuarentena",
    "btn.shredfile": "Triturar archivos…", "btn.shreddir": "Triturar carpeta…", "btn.shred": "Triturar definitivamente",
    "tip.min": "Minimizar", "tip.max": "Maximizar", "tip.close": "Cerrar",
    "nav.home": "Inicio", "nav.scan": "Análisis inteligente", "nav.clean": "Limpieza", "nav.space": "Análisis de disco",
    "nav.startup": "Inicio", "nav.apps": "Aplicaciones", "nav.toolbox": "Herramientas", "nav.settings": "Ajustes",
    "risk.safe": "Seguro", "risk.low": "Riesgo bajo", "risk.confirm": "Revisar", "risk.high": "Riesgo alto",
    "cat.system": "Sistema", "cat.apps": "Aplicaciones", "cat.images": "Imágenes", "cat.videos": "Vídeos",
    "cat.audio": "Audio", "cat.documents": "Documentos", "cat.archives": "Comprimidos", "cat.other": "Otros",
    "time.now": "Ahora mismo", "time.minago": "hace {0} min", "time.today": "Hoy {0}", "time.yesterday": "Ayer {0}",
    "home.slogan": "Análisis periódicos mantienen tu PC al máximo",
    "home.status.good": "Tu PC está en buen estado", "home.status.suggest": "Se recomienda una limpieza", "home.status.tight": "Poco espacio en disco",
    "home.status.suggest.detail": "{0} de datos limpiables y {1} elementos de inicio de alto impacto",
    "home.status.tight.detail": "Menos del 10 % libre en la unidad del sistema: limpia ahora",
    "home.status.lastscan": "Último análisis: {0}", "home.noscan": "Aún sin analizar", "home.noscan.detail": "Pulsa «Analizar ahora» para empezar",
    "home.card.junk": "Datos limpiables", "home.card.junk.note": "Analiza para ver el espacio recuperable", "home.card.junk.lastscan": "Último análisis {0}",
    "home.card.startup": "Elementos de inicio", "home.card.startup.note": "elementos se ejecutan al arrancar", "home.card.startup.note.high": "elementos de alto impacto pueden ralentizar el arranque",
    "home.card.large": "Archivos grandes", "home.card.large.note": "Analiza para buscarlos", "home.card.large.analyzed": "Analizado",
    "home.card.large.analyzed.note": "Pulsa para ver los detalles", "home.card.large.pending": "Pendiente",
    "home.card.apps": "Aplicaciones", "home.card.apps.note": "Pulsa para gestionar",
    "home.disk.title": "Disco (C:)", "home.disk.title.disk": "Disco ({0})", "home.disk.total": "Total —",
    "home.disk.used": "Usado —", "home.disk.free": "Libre —", "home.disk.total.f": "Total {0}",
    "home.disk.used.f": "Usado {0} ({1:F1} %)", "home.disk.free.f": "Libre {0} ({1:F1} %)", "home.disk.more": "¿Dónde está mi espacio? →",
    "home.space.title": "Análisis de disco", "home.space.empty": "Esta unidad aún no se ha analizado",
    "home.activity.title": "Actividad reciente", "home.activity.empty": "Sin actividad. Lanza un análisis",
    "home.suggest.title": "Sugerencias", "home.suggest.empty": "Todo bien: no hay nada que atender",
    "home.suggest.note.safe": "Seguro de limpiar, sin impacto en el sistema", "home.suggest.clean": "Limpiar ahora", "home.suggest.optimize": "Optimizar",
    "home.suggest.startup.title": "Sugerencia de inicio", "home.suggest.startup.note": "{0} elementos de inicio de alto impacto. Considera optimizarlos",
    "home.hero.note": "Un PC más limpio,\n¡más fluido!",
    "scan.start": "Iniciar análisis", "scan.cover": "Un solo análisis: datos del sistema · cachés de navegador · cachés de apps · papelera",
    "scan.privacy": "Todo se ejecuta en local; solo se preseleccionan elementos seguros, los de riesgo nunca.",
    "scan.preparing": "Preparando…", "scan.found": "Encontrado —", "scan.done": "Análisis completado", "scan.reselectall": "Seleccionar elementos seguros",
    "scan.group.safe": "Limpieza segura", "scan.group.safe.note": "Datos temporales del sistema y las apps; se pueden eliminar sin riesgo",
    "scan.group.cache": "Cachés de navegador y apps", "scan.group.cache.note": "Datos de caché; las apps los vuelven a descargar",
    "scan.group.check": "Revisar", "scan.group.check.note": "Confirma que ya no los necesitas antes de limpiar",
    "result.title.found": "Análisis completado: {0} recuperables", "result.title.clean": "¡Análisis completado: todo limpio!",
    "result.sub": "{0} · {1} categorías analizadas",
    "row.files": "{0} archivos", "row.restore": "restaurable desde cuarentena", "row.direct": "se elimina directamente",
    "row.running": "{0} procesos relacionados en ejecución", "row.impact.tip": "Impacto: {0}",
    "clean.title": "Limpiando…", "clean.freed": "Liberado —",
    "done.title": "Limpieza completada", "done.cancelled": "Limpieza interrumpida", "done.partial": "Limpieza completada (algunos omitidos)",
    "done.freed.total": "{0} liberados en total", "done.note.quarantine": "Los archivos en cuarentena se conservan {0} días y se restauran desde Herramientas.",
    "done.note.skip": "Los archivos omitidos están en uso; ciérralos y vuelve a intentarlo más tarde.",
    "done.stat.ok": "Limpiados", "done.stat.quar": "En cuarentena", "done.stat.skip": "Omitidos (en uso)", "done.stat.fail": "Fallidos",
    "clean.tab.system": "Sistema", "clean.tab.app": "Cachés de apps", "clean.tab.browser": "Navegadores",
    "clean.tab.privacy": "Rastros de privacidad", "clean.tab.recycle": "Papelera",
    "clean.tabnote.0": "Archivos temporales, registros e informes de fallos: solo se preseleccionan elementos seguros",
    "clean.tabnote.1": "Cachés y registros de apps de mensajería y oficina: tus chats y documentos no se tocan",
    "clean.tabnote.2": "Cachés de navegación: no afectan a sesiones, contraseñas ni historial",
    "clean.tabnote.3": "Datos personales: desmarcados por defecto; revisa cada impacto con cuidado",
    "clean.tabnote.4": "Confirma que la papelera no contiene nada útil antes de vaciarla",
    "clean.privacy.banner": "Los elementos de privacidad están desmarcados por defecto. Lee cada impacto: limpiar cookies cierra sesiones; el historial borrado no se recupera.",
    "clean.privacy.warn": "Los elementos de privacidad no se pueden restaurar tras la limpieza.",
    "clean.recycle.desc": "Al vaciarla, los archivos se eliminan definitivamente. Puedes abrir la papelera para revisarla antes.",
    "clean.empty.before": "Pulsa «Escanear grupo» abajo para revisar esta categoría", "clean.empty.clean": "Esta categoría ya está limpia",
    "clean.empty.group": "Pulsa «Escanear grupo» abajo para revisar esta categoría",
    "recycle.info": "{0} elementos, {1}", "recycle.empty": "La papelera está vacía",
    "recycle.confirm.title": "¿Vaciar la papelera?", "recycle.confirm.msg": "{0} archivos ({1}) se eliminarán definitivamente. No se puede deshacer.",
    "toast.cleandone": "Limpieza completada: {0} liberados", "toast.skipped": " ({0} omitidos)", "toast.binemptied": "Papelera vaciada",
    "toast.failed": "Error en la operación",
    "dlg.clean.selected.title": "¿Limpiar los elementos seleccionados?", "dlg.clean.amount": "A punto de limpiar {0} de datos.",
    "dlg.clean.nrules": "Se limpiarán {0} categorías, {1} en total.", "dlg.clean.confirmitems": "Elementos que requieren confirmación:",
    "dlg.clean.quarantinehint": "Los archivos restaurables se moverán a la cuarentena.",
    "dlg.quickclean.title": "¿Limpiar {0}?", "dlg.quickclean.msg": "Se liberará ~{0}.\nLos archivos restaurables irán a la cuarentena.",
    "space.tab.overview": "Resumen", "space.tab.large": "Archivos grandes", "space.tree.title": "Ranking de carpetas",
    "space.tree.hint": "Haz clic para expandir; enlaces del sistema y carpetas inaccesibles se omiten",
    "space.empty": "Esta unidad aún no se ha analizado. Pulsa «Analizar» arriba (puedes cancelar en cualquier momento)",
    "space.scanning": "Analizando disco…", "space.cancelled": "Análisis cancelado", "space.failed": "Error de análisis: ",
    "space.done": "Análisis completado en {0:F0} s", "space.rendererror": "Error al mostrar los resultados; consulta el registro",
    "space.scanned": "{0:N0} archivos analizados", "space.total": "total {0}",
    "space.used.f": "Usado {0} / {1} ({2:F1} %), libre {3}", "space.used.f2": "Usado {0} / {1}, libre {2}",
    "space.analyzed.f": "Analizado {0} · {1:N0} archivos · {2:F0} s", "space.lastanalysis": "Último análisis: {0}",
    "space.notanalyzed": "Esta unidad aún no se ha analizado", "space.large.filter": "Filtro de tamaño",
    "space.large.none": "No hay archivos mayores de {0:F0} MB", "space.modified": "Modificado", "space.file": "ARCHIVO",
    "space.recycle.title": "¿Mover a la papelera?", "space.recycle.msg": "{0} ({1}) se moverá a la papelera. Puedes restaurarlo cuando quieras.",
    "toast.whitelisted": "Añadido a la lista blanca: se omitirá en análisis y limpiezas",
    "toast.largecleaned": "Archivo grande limpiado {0}", "toast.recycled": "Movido a la papelera: {0} liberados",
    "toast.recyclefailed": "No se pudo mover a la papelera; el archivo puede estar en uso",
    "startup.desc": "Las apps desactivadas se pueden abrir manualmente; cada cambio se puede revertir.",
    "startup.col.toggle": "Estado", "startup.col.impact": "Impacto", "startup.col.source": "Origen", "startup.col.suggest": "Consejo",
    "startup.loading": "Cargando elementos de inicio…", "startup.empty": "No hay elementos coincidentes", "startup.systemchip": "Componente del sistema",
    "startup.src.reghkcu": "Registro (usuario)", "startup.src.reghklm": "Registro (equipo)",
    "startup.src.folderuser": "Carpeta Inicio (usuario)", "startup.src.foldercommon": "Carpeta Inicio (todos)",
    "startup.src.task": "Tarea programada", "startup.impact.high": "Alto", "startup.impact.med": "Medio",
    "startup.impact.low": "Bajo", "startup.impact.unknown": "Sin medir",
    "startup.suggest.off": "Considera desactivarlo", "startup.suggest.system": "Componente del sistema", "startup.suggest.keep": "Mantener",
    "startup.enabled": "Activado", "startup.disabled": "Desactivado", "startup.toggled": "{0} el elemento de inicio «{1}»",
    "apps.desc": "La desinstalación usa el desinstalador de la propia app; después puedes limpiar los restos confirmados (a cuarentena, restaurables).",
    "apps.sort.name": "Por nombre", "apps.sort.size": "Por tamaño", "apps.sort.date": "Por fecha de instalación",
    "apps.col.name": "Aplicación", "apps.col.publisher": "Editor", "apps.col.size": "Tamaño", "apps.col.date": "Instalado",
    "apps.loading": "Cargando aplicaciones instaladas…", "apps.empty": "No hay apps coincidentes", "apps.store": "Aplicación de Microsoft Store",
    "apps.unknown": "Desconocido", "apps.uninstall.title": "¿Desinstalar {0}?", "apps.uninstall.start": "Iniciar desinstalación",
    "apps.uninstall.msg": "Tamaño: {0}\n\nSe iniciará el desinstalador de la propia aplicación: sigue su asistente.",
    "apps.waiting": "Esperando a que «{0}» se desinstale…\nContinúa automáticamente al terminar",
    "apps.notdetected": "No se detectó la desinstalación; puede haberse cancelado",
    "apps.uninstalled.toast": "«{0}» se ha desinstalado", "apps.uninstalled.log": "Aplicación desinstalada «{0}»",
    "apps.uninstall.failed": "No se pudo iniciar el desinstalador: ",
    "leftover.title": "Posibles restos encontrados", "leftover.title.f": "Restos de «{0}»",
    "leftover.desc": "Carpetas de datos y claves de registro de esta aplicación. Los marcados van a cuarentena (restaurables).",
    "leftover.skip": "No limpiar, terminar", "leftover.clean": "Limpiar marcados", "leftover.reg": "Clave de registro (con copia de seguridad)",
    "leftover.datadir": "Carpeta de datos", "leftover.installdir": "Carpeta de instalación",
    "tool.desc": "Los archivos triturados no pasan por la papelera; los de cuarentena son restaurables; los duplicados se detectan por contenido.",
    "tool.quarantine.title": "Cuarentena", "tool.quar.empty": "La cuarentena está vacía",
    "tool.quar.summary": "{0} elementos, {1}; se eliminan tras {2} días",
    "tool.quar.daysleft": "{0} días restantes", "tool.purge.title": "¿Vaciar cuarentena?",
    "tool.purge.msg": "{0} elementos de la cuarentena se eliminarán definitivamente. No se puede deshacer.",
    "tool.shred.title": "Trituradora de archivos", "tool.shred.desc": "Elimina archivos definitivamente sin pasar por la papelera. Nota: en SSD no se puede garantizar el borrado físico inmediato. Irreversible: elige con cuidado.",
    "tool.shred.confirm.title": "¿Triturar?", "tool.shred.confirm.msg": "{0}\n\n{1} se sobrescribirá y eliminará definitivamente, sin pasar por la papelera.\n\n¡No se puede deshacer!",
    "tool.shred.log": "{0} «{1}» triturado", "tool.folder": "carpeta", "tool.file": "archivo",
    "tool.dup.title": "Archivos duplicados", "tool.dup.desc": "Los duplicados se confirman por hash de contenido (nunca por nombre). Ámbito por defecto: Imágenes, Vídeos y Descargas.",
    "tool.dup.none": "No se encontraron duplicados", "tool.dup.summary": "{0} grupos de duplicados, {1} recuperables",
    "tool.dup.progress": "{0:N0} archivos analizados…", "tool.dup.more": "… {0} grupos más sin mostrar",
    "tool.dup.group": "{0} archivos idénticos · {1} cada uno · {2} recuperables", "tool.dup.tip": "Marcado = eliminar esta copia",
    "tool.dup.clean.title": "¿Eliminar las copias marcadas?", "tool.dup.clean.msg": "{0} archivos ({1}) se moverán a la papelera (restaurables).",
    "tool.history.title": "Historial", "tool.win.title": "Herramientas de Windows", "tool.win.desc": "Accesos directos a herramientas del sistema: seguras",
    "tool.win.taskmgr": "Administrador de tareas", "tool.win.taskmgr.d": "Procesos y rendimiento",
    "tool.win.storage": "Almacenamiento", "tool.win.storage.d": "Gestionar el almacenamiento",
    "tool.win.diskmgmt": "Administración de discos", "tool.win.diskmgmt.d": "Gestionar particiones y discos",
    "tool.win.devmgmt": "Administrador de dispositivos", "tool.win.devmgmt.d": "Hardware y controladores",
    "tool.win.control": "Panel de control", "tool.win.control.d": "Configuración clásica",
    "tool.win.msinfo": "Información del sistema", "tool.win.msinfo.d": "Ver la configuración del sistema",
    "tool.win.update": "Windows Update", "tool.win.update.d": "Buscar actualizaciones",
    "tool.win.restore": "Restaurar sistema", "tool.win.restore.d": "Crear o usar puntos de restauración",
    "history.empty": "Sin actividad", "history.clear.title": "¿Borrar el historial?", "history.clear.msg": "Se eliminarán todos los registros.",
    "history.type.clean": "Limpieza", "history.type.autoclean": "Auto", "history.type.restore": "Restauración",
    "history.type.uninstall": "Desinstalación", "history.type.startup": "Inicio", "history.type.quarantine": "Cuarentena",
    "history.type.shred": "Triturado", "history.type.other": "Otro",
    "settings.title": "Ajustes", "settings.sec.general": "General", "settings.sec.exclude": "Exclusiones y lista blanca",
    "settings.sec.notify": "Notificaciones", "settings.sec.advanced": "Avanzado", "settings.sec.privacy": "Privacidad", "settings.sec.about": "Acerca de",
    "settings.exc.desc": "Estas carpetas y archivos se omiten en todos los análisis y limpiezas.", "settings.exc.empty": "Sin exclusiones ni lista blanca",
    "settings.whitelist": "Lista blanca", "settings.excluded": "Excluido",
    "settings.btn.addexclude": "Añadir carpeta excluida", "settings.btn.addwhitelist": "Añadir a la lista blanca",
    "settings.pick.whitelist": "Elige un archivo para la lista blanca", "settings.pick.exclude": "Elige una carpeta a excluir",
    "settings.days": "días", "settings.threads": "subprocesos",
    "settings.theme.light": "Claro", "settings.theme.dark": "Oscuro", "settings.theme.system": "Según el sistema",
    "settings.freq.daily": "Cada día", "settings.freq.weekly": "Cada semana", "settings.freq.monthly": "Cada mes",
    "settings.lang.auto": "Idioma del sistema",
    "settings.row.language": "Idioma", "settings.row.language.d": "Se aplica al instante",
    "settings.row.autostart": "Ejecutar al iniciar Windows", "settings.row.autostart.d": "Permanece en la bandeja sin hacer nada por sí mismo",
    "settings.row.mintotray": "Minimizar a la bandeja", "settings.row.mintotray.d": "El botón minimizar oculta en la bandeja",
    "settings.row.closetotray": "Cerrar minimiza a la bandeja", "settings.row.closetotray.d": "El botón cerrar pregunta y minimiza en lugar de salir",
    "settings.row.theme": "Tema",
    "settings.row.quarantine": "Cuarentena tras limpiar", "settings.row.quarantine.d": "Los archivos que no son caché van primero a cuarentena (recomendado)",
    "settings.row.quarantine.days": "Retención en cuarentena", "settings.row.quarantine.days.d": "Se eliminan automáticamente al expirar",
    "settings.row.autoclean": "Limpieza automática", "settings.row.autoclean.d": "Limpia elementos seguros según programación",
    "settings.row.autoclean.freq": "Frecuencia", "settings.row.autoclean.freq.d": "En segundo plano mientras la app esté abierta",
    "settings.row.notifydisk": "Aviso de poco espacio", "settings.row.notifydisk.d": "Avisa cuando la unidad del sistema baja del 10 % (poco frecuente)",
    "settings.row.notifyauto": "Resultados de limpieza automática", "settings.row.notifyweekly": "Informe semanal",
    "settings.row.notifynews": "Novedades", "settings.row.notifynews.d": "Novedades y eventos, desactivado por defecto",
    "settings.row.threads": "Subprocesos de análisis", "settings.row.threads.d": "Más subprocesos = más rápido; reduce en HDD",
    "settings.row.hidden": "Analizar archivos ocultos", "settings.row.junction": "Seguir enlaces de directorios (Junctions)",
    "settings.row.junction.d": "Seguir enlaces puede duplicar estadísticas; desactivado por defecto",
    "settings.row.stats": "Estadísticas anónimas", "settings.row.stats.d": "Solo recuentos y códigos de error; esta versión no envía nada",
    "settings.row.crash": "Informes de fallos",
    "settings.privacy.desc": "Todos los datos de análisis se quedan en este equipo. Nunca se recopilan ni envían nombres, rutas ni contenidos.",
    "settings.about.slogan": "Limpiar con claridad, optimizar con tranquilidad.", "settings.about.support": "Soporte y comentarios",
    "settings.about.site": "Sitio web", "settings.about.email": "Correo", "settings.about.repo": "Código fuente",
    "settings.about.wechat": "Escanea o busca «AI虚拟助理» en WeChat para consejos y novedades.",
    "wizard.welcome": "Bienvenido a CleanMaster",
    "wizard.slogan": "Limpiar con claridad, optimizar con tranquilidad.\nSolo hacemos limpieza explicable, previsualizable y restaurable.",
    "wizard.privacy.title": "Nuestra promesa de privacidad",
    "wizard.privacy.items": "· Todos los resultados, nombres y rutas se quedan en este PC.\n· Sin telemetría por defecto; nunca se sube contenido de archivos.\n· Las limpiezas importantes van a cuarentena: restaurables 7~30 días.\n· Siempre se previsualiza antes de eliminar: nunca en silencio.",
    "wizard.auto.title": "¿Activar limpieza automática?", "wizard.auto.desc": "Solo limpia elementos seguros (temporales, cachés de apps), una vez por semana.",
    "wizard.auto.yes": "Activar", "wizard.auto.no": "Ahora no", "wizard.next": "Empezar", "wizard.next2": "Siguiente",
    "tray.open": "Abrir CleanMaster", "tray.quickscan": "Análisis rápido", "tray.exit": "Salir",
    "tray.autoclean": "Limpieza automática: ", "tray.on": "activada", "tray.off": "desactivada",
    "dlg.exit.title": "¿Salir de CleanMaster?", "dlg.exit.msg": "Al salir se detienen la limpieza automática y la supervisión del disco.",
    "toast.traymin": "Minimizado a la bandeja; clic derecho en el icono para salir",
    "toast.scanstopped": "Análisis detenido", "toast.scanfailed": "Error de análisis: ", "toast.noselect": "Selecciona primero elementos para limpiar",
    "toast.cleancancelled": "Limpieza cancelada", "toast.cleanfailed": "Error de limpieza: ",
    "toast.nothing": "No hay nada que limpiar", "toast.cleaned": "Limpieza completada: {0} liberados",
    "toast.readfailed": "Error al cargar: ", "toast.langapplied": "Idioma cambiado",
}

DE = {
    "common.selected": "Ausgewählt", "common.freeable": "freiwerdend", "common.viewall": "Alle anzeigen",
    "common.loading": "Wird geladen…", "common.scanning": "Scanne…", "common.n.items": "{0} Elemente",
    "common.approx": "~", "btn.cancel": "Abbrechen", "btn.exit": "Beenden", "btn.refresh": "Aktualisieren",
    "btn.stopscan": "Scan stoppen", "btn.rescan": "Erneut scannen", "btn.restore": "Wiederherstellen", "btn.deleteperm": "Endgültig löschen",
    "btn.uninstall": "Deinstallieren", "btn.recycle": "In den Papierkorb", "btn.remove": "Entfernen", "btn.analyze.start": "Analysieren",
    "btn.scan.now": "Jetzt scannen", "btn.more": "Mehr Funktionen", "btn.clean.selected": "Auswahl bereinigen",
    "btn.clean.start": "Bereinigung starten", "btn.done.home": "Zurück zur Startseite", "btn.done.quarantine": "Quarantäne öffnen",
    "btn.emptybin": "Papierkorb leeren", "btn.openbin": "Papierkorb öffnen", "btn.scangroup": "Gruppe scannen",
    "btn.cleansel": "Auswahl bereinigen", "btn.dupscan": "Scan starten", "btn.dup.rescan": "Erneut scannen",
    "btn.dupkeepnew": "Neueste behalten", "btn.dupclean": "Auswahl in den Papierkorb",
    "btn.clearhistory": "Verlauf leeren", "btn.clearlocal": "Lokalen Verlauf löschen", "btn.purge": "Quarantäne leeren",
    "btn.shredfile": "Dateien schreddern…", "btn.shreddir": "Ordner schreddern…", "btn.shred": "Endgültig schreddern",
    "tip.min": "Minimieren", "tip.max": "Maximieren", "tip.close": "Schließen",
    "nav.home": "Start", "nav.scan": "Smart-Scan", "nav.clean": "Bereinigung", "nav.space": "Speicheranalyse",
    "nav.startup": "Autostart", "nav.apps": "Apps", "nav.toolbox": "Werkzeuge", "nav.settings": "Einstellungen",
    "risk.safe": "Sicher", "risk.low": "Geringes Risiko", "risk.confirm": "Prüfen", "risk.high": "Hohes Risiko",
    "cat.system": "System", "cat.apps": "Apps", "cat.images": "Bilder", "cat.videos": "Videos",
    "cat.audio": "Audio", "cat.documents": "Dokumente", "cat.archives": "Archive", "cat.other": "Sonstige",
    "time.now": "gerade eben", "time.minago": "vor {0} Min.", "time.today": "Heute {0}", "time.yesterday": "Gestern {0}",
    "home.slogan": "Regelmäßige Scans halten den PC in Bestform",
    "home.status.good": "Dein PC ist in gutem Zustand", "home.status.suggest": "Eine Bereinigung wird empfohlen", "home.status.tight": "Wenig Speicherplatz",
    "home.status.suggest.detail": "{0} bereinigbare Daten und {1} Startprogramme mit hoher Auswirkung gefunden",
    "home.status.tight.detail": "Weniger als 10 % frei auf dem Systemlaufwerk — jetzt aufräumen",
    "home.status.lastscan": "Letzter Scan: {0}", "home.noscan": "Noch nicht gescannt", "home.noscan.detail": "Klicke auf „Jetzt scannen“, um zu starten",
    "home.card.junk": "Bereinigbarer Müll", "home.card.junk.note": "Scannen, um freien Speicher zu sehen", "home.card.junk.lastscan": "Letzter Scan {0}",
    "home.card.startup": "Autostart", "home.card.startup.note": "Elemente starten mit Windows", "home.card.startup.note.high": "Einträge mit hoher Auswirkung können den Start verlangsamen",
    "home.card.large": "Große Dateien", "home.card.large.note": "Per Analyse finden", "home.card.large.analyzed": "Analysiert",
    "home.card.large.analyzed.note": "Für Details klicken", "home.card.large.pending": "Ausstehend",
    "home.card.apps": "Installierte Apps", "home.card.apps.note": "Zum Verwalten klicken",
    "home.disk.title": "Speicher (C:)", "home.disk.title.disk": "Speicher ({0})", "home.disk.total": "Gesamt —",
    "home.disk.used": "Belegt —", "home.disk.free": "Frei —", "home.disk.total.f": "Gesamt {0}",
    "home.disk.used.f": "Belegt {0} ({1:F1} %)", "home.disk.free.f": "Frei {0} ({1:F1} %)", "home.disk.more": "Wohin geht der Speicher →",
    "home.space.title": "Speicheranalyse", "home.space.empty": "Dieses Laufwerk wurde noch nicht analysiert",
    "home.activity.title": "Letzte Aktivitäten", "home.activity.empty": "Noch keine Aktivitäten — starte einen Scan",
    "home.suggest.title": "Smarte Vorschläge", "home.suggest.empty": "Alles bestens — nichts zu tun",
    "home.suggest.note.safe": "Sicher zu bereinigen, ohne Auswirkung", "home.suggest.clean": "Jetzt bereinigen", "home.suggest.optimize": "Optimieren",
    "home.suggest.startup.title": "Autostart-Hinweis", "home.suggest.startup.note": "{0} Autostart-Einträge mit hoher Auswirkung gefunden",
    "home.hero.note": "Sauberer PC,\nflotter Lauf!",
    "scan.start": "Scan starten", "scan.cover": "Ein Scan für: Systemmüll · Browser-Caches · App-Caches · Papierkorb",
    "scan.privacy": "Alles läuft lokal; nur sichere Elemente sind vorausgewählt, riskante nie.",
    "scan.preparing": "Vorbereiten…", "scan.found": "Gefunden —", "scan.done": "Scan abgeschlossen", "scan.reselectall": "Sichere Elemente wählen",
    "scan.group.safe": "Sicher bereinigbar", "scan.group.safe.note": "Temporäre Daten von System und Apps — gefahrlos entfernbar",
    "scan.group.cache": "Browser- & App-Caches", "scan.group.cache.note": "Cache-Daten; Apps laden sie bei Bedarf neu",
    "scan.group.check": "Bitte prüfen", "scan.group.check.note": "Bestätige, dass du diese Inhalte nicht mehr brauchst",
    "result.title.found": "Scan abgeschlossen — {0} freigebbar", "result.title.clean": "Scan abgeschlossen — alles sauber!",
    "result.sub": "{0} · {1} Kategorien gescannt",
    "row.files": "{0} Dateien", "row.restore": "über Quarantäne wiederherstellbar", "row.direct": "direkt gelöscht",
    "row.running": "{0} zugehörige Prozesse aktiv", "row.impact.tip": "Auswirkung: {0}",
    "clean.title": "Bereinige…", "clean.freed": "Freigegeben —",
    "done.title": "Bereinigung abgeschlossen", "done.cancelled": "Bereinigung abgebrochen", "done.partial": "Bereinigung abgeschlossen (einige übersprungen)",
    "done.freed.total": "{0} insgesamt freigegeben", "done.note.quarantine": "Quarantäne-Dateien bleiben {0} Tage erhalten und sind in den Werkzeugen wiederherstellbar.",
    "done.note.skip": "Übersprungene Dateien werden von anderen Programmen verwendet; später erneut versuchen.",
    "done.stat.ok": "Bereinigt", "done.stat.quar": "In Quarantäne", "done.stat.skip": "Übersprungen (belegt)", "done.stat.fail": "Fehlgeschlagen",
    "clean.tab.system": "Systemmüll", "clean.tab.app": "App-Caches", "clean.tab.browser": "Browser",
    "clean.tab.privacy": "Datenspuren", "clean.tab.recycle": "Papierkorb",
    "clean.tabnote.0": "Tempdateien, Protokolle und Absturzberichte von System und Apps — nur sichere Elemente vorausgewählt",
    "clean.tabnote.1": "Caches und Protokolle von Chat- & Office-Apps — Chats und Dokumente bleiben unberührt",
    "clean.tabnote.2": "Browser-Caches für schnelleres Surfen — Logins, Passwörter und Verlauf bleiben unberührt",
    "clean.tabnote.3": "Persönliche Daten — standardmäßig abgewählt; jede Auswirkung genau prüfen",
    "clean.tabnote.4": "Prüfe, ob der Papierkorb nichts Wichtiges enthält, bevor du ihn leerst",
    "clean.privacy.banner": "Datenschutz-Elemente sind standardmäßig abgewählt. Lies jede Auswirkung: Cookies löschen meldet dich ab; gelöschter Verlauf ist unwiederbringlich.",
    "clean.privacy.warn": "Datenschutz-Elemente können nach der Bereinigung nicht wiederhergestellt werden.",
    "clean.recycle.desc": "Beim Leeren des Papierkorbs werden die Dateien endgültig gelöscht. Du kannst ihn vorher öffnen und prüfen.",
    "clean.empty.before": "Klicke unten auf „Gruppe scannen“, um diese Kategorie zu prüfen", "clean.empty.clean": "Diese Kategorie ist sauber",
    "clean.empty.group": "Klicke unten auf „Gruppe scannen“, um diese Kategorie zu prüfen",
    "recycle.info": "{0} Elemente, {1}", "recycle.empty": "Der Papierkorb ist leer",
    "recycle.confirm.title": "Papierkorb leeren?", "recycle.confirm.msg": "{0} Dateien ({1}) werden endgültig gelöscht. Nicht wiederherstellbar.",
    "toast.cleandone": "Bereinigung abgeschlossen — {0} freigegeben", "toast.skipped": " ({0} übersprungen)", "toast.binemptied": "Papierkorb geleert",
    "toast.failed": "Vorgang fehlgeschlagen",
    "dlg.clean.selected.title": "Auswahl bereinigen?", "dlg.clean.amount": "{0} an Daten werden bereinigt.",
    "dlg.clean.nrules": "{0} Kategorien mit insgesamt {1} werden bereinigt.", "dlg.clean.confirmitems": "Zu prüfende Elemente:",
    "dlg.clean.quarantinehint": "Wiederherstellbare Dateien kommen in die Quarantäne.",
    "dlg.quickclean.title": "{0} bereinigen?", "dlg.quickclean.msg": "Etwa {0} werden frei.\nWiederherstellbare Dateien kommen in die Quarantäne.",
    "space.tab.overview": "Übersicht", "space.tab.large": "Große Dateien", "space.tree.title": "Ordner-Rangliste",
    "space.tree.hint": "Zum Aufklappen klicken; Systemlinks und unzugängliche Ordner werden übersprungen",
    "space.empty": "Dieses Laufwerk wurde noch nicht analysiert. Oben auf „Analysieren“ klicken (jederzeit abbrechbar)",
    "space.scanning": "Laufwerk wird analysiert…", "space.cancelled": "Analyse abgebrochen", "space.failed": "Analyse fehlgeschlagen: ",
    "space.done": "Analyse in {0:F0} s abgeschlossen", "space.rendererror": "Fehler beim Anzeigen der Ergebnisse — siehe Protokoll",
    "space.scanned": "{0:N0} Dateien gescannt", "space.total": "gesamt {0}",
    "space.used.f": "Belegt {0} / {1} ({2:F1} %), frei {3}", "space.used.f2": "Belegt {0} / {1}, frei {2}",
    "space.analyzed.f": "Analysiert {0} · {1:N0} Dateien · {2:F0} s", "space.lastanalysis": "Letzte Analyse: {0}",
    "space.notanalyzed": "Dieses Laufwerk wurde noch nicht analysiert", "space.large.filter": "Größenfilter",
    "space.large.none": "Keine Dateien über {0:F0} MB gefunden", "space.modified": "Geändert", "space.file": "DATEI",
    "space.recycle.title": "In den Papierkorb verschieben?", "space.recycle.msg": "{0} ({1}) wird in den Papierkorb verschoben. Jederzeit wiederherstellbar.",
    "toast.whitelisted": "Zur Whitelist hinzugefügt — Scans und Bereinigungen überspringen diese Datei",
    "toast.largecleaned": "Große Datei bereinigt {0}", "toast.recycled": "In den Papierkorb verschoben — {0} frei",
    "toast.recyclefailed": "Verschieben fehlgeschlagen; Datei ist evtl. belegt",
    "startup.desc": "Deaktivierte Apps lassen sich weiterhin manuell öffnen; jede Änderung bleibt wiederherstellbar.",
    "startup.col.toggle": "Status", "startup.col.impact": "Auswirkung", "startup.col.source": "Quelle", "startup.col.suggest": "Tipp",
    "startup.loading": "Autostart-Einträge werden geladen…", "startup.empty": "Keine passenden Einträge", "startup.systemchip": "Systemkomponente",
    "startup.src.reghkcu": "Registrierung (Benutzer)", "startup.src.reghklm": "Registrierung (Computer)",
    "startup.src.folderuser": "Autostart-Ordner (Benutzer)", "startup.src.foldercommon": "Autostart-Ordner (alle)",
    "startup.src.task": "Geplante Aufgabe", "startup.impact.high": "Hoch", "startup.impact.med": "Mittel",
    "startup.impact.low": "Niedrig", "startup.impact.unknown": "Unbewertet",
    "startup.suggest.off": "Deaktivieren erwägen", "startup.suggest.system": "Systemkomponente", "startup.suggest.keep": "Behalten",
    "startup.enabled": "Aktiviert", "startup.disabled": "Deaktiviert", "startup.toggled": "Autostart „{1}“ {0}",
    "apps.desc": "Die Deinstallation startet das eigene Deinstallationsprogramm der App; danach können bestätigte Reste bereinigt werden (in Quarantäne, wiederherstellbar).",
    "apps.sort.name": "Nach Name", "apps.sort.size": "Nach Größe", "apps.sort.date": "Nach Installationsdatum",
    "apps.col.name": "App", "apps.col.publisher": "Herausgeber", "apps.col.size": "Größe", "apps.col.date": "Installiert am",
    "apps.loading": "Installierte Apps werden geladen…", "apps.empty": "Keine passenden Apps", "apps.store": "Microsoft Store App",
    "apps.unknown": "Unbekannt", "apps.uninstall.title": "{0} deinstallieren?", "apps.uninstall.start": "Deinstallation starten",
    "apps.uninstall.msg": "App-Größe: {0}\n\nDas eigene Deinstallationsprogramm der App wird gestartet — folge seinem Assistenten.",
    "apps.waiting": "Warte auf Deinstallation von „{0}“…\nFährt automatisch fort, wenn fertig",
    "apps.notdetected": "Deinstallation nicht erkannt — evtl. abgebrochen",
    "apps.uninstalled.toast": "„{0}“ wurde deinstalliert", "apps.uninstalled.log": "App „{0}“ deinstalliert",
    "apps.uninstall.failed": "Deinstallationsprogramm konnte nicht gestartet werden: ",
    "leftover.title": "Mögliche Reste gefunden", "leftover.title.f": "Reste von „{0}“",
    "leftover.desc": "Datenordner und Einstellungsschlüssel, die eindeutig zu dieser App gehören. Ausgewählte Elemente kommen in die Quarantäne (wiederherstellbar).",
    "leftover.skip": "Nicht bereinigen, fertig", "leftover.clean": "Auswahl bereinigen", "leftover.reg": "Registrierungsschlüssel (gesichert, dann entfernt)",
    "leftover.datadir": "Datenordner", "leftover.installdir": "Installationsordner",
    "tool.desc": "Geschredderte Dateien umgehen den Papierkorb; Quarantäne-Dateien sind wiederherstellbar; Duplikate werden per Inhalts-Hash erkannt.",
    "tool.quarantine.title": "Quarantäne", "tool.quar.empty": "Die Quarantäne ist leer",
    "tool.quar.summary": "{0} Elemente, {1}; automatische Löschung nach {2} Tagen",
    "tool.quar.daysleft": "{0} Tage verbleibend", "tool.purge.title": "Quarantäne leeren?",
    "tool.purge.msg": "{0} Quarantäne-Elemente werden endgültig gelöscht. Nicht wiederherstellbar.",
    "tool.shred.title": "Datei-Shredder", "tool.shred.desc": "Löscht Dateien endgültig, ohne den Papierkorb. Hinweis: Bei SSDs kann ein sofortiges physisches Überschreiben nicht garantiert werden. Irreversibel — sorgfältig wählen.",
    "tool.shred.confirm.title": "Dieses Element schreddern?", "tool.shred.confirm.msg": "{0}\n\n{1} wird überschrieben und endgültig gelöscht — ohne den Papierkorb.\n\nNicht reversibel!",
    "tool.shred.log": "{0} „{1}“ geschreddert", "tool.folder": "Ordner", "tool.file": "Datei",
    "tool.dup.title": "Duplizierte Dateien", "tool.dup.desc": "Duplikate werden per Inhalts-Hash bestätigt (nie per Dateiname). Standardbereich: Bilder, Videos und Downloads.",
    "tool.dup.none": "Keine Duplikate gefunden", "tool.dup.summary": "{0} Duplikatgruppen, {1} freigebbar",
    "tool.dup.progress": "{0:N0} Dateien gescannt…", "tool.dup.more": "… {0} weitere Gruppen nicht angezeigt",
    "tool.dup.group": "{0} identische Dateien · je {1} · {2} freigebbar", "tool.dup.tip": "Angehakt = diese Kopie löschen",
    "tool.dup.clean.title": "Ausgewählte Kopien löschen?", "tool.dup.clean.msg": "{0} Dateien ({1}) werden in den Papierkorb verschoben (wiederherstellbar).",
    "tool.history.title": "Verlauf", "tool.win.title": "Windows-Werkzeuge", "tool.win.desc": "Direkte Zugriffe auf eingebaute Systemwerkzeuge — sicher",
    "tool.win.taskmgr": "Task-Manager", "tool.win.taskmgr.d": "Prozesse und Leistung",
    "tool.win.storage": "Speichereinstellungen", "tool.win.storage.d": "Speicher verwalten",
    "tool.win.diskmgmt": "Datenträgerverwaltung", "tool.win.diskmgmt.d": "Partitionen und Laufwerke verwalten",
    "tool.win.devmgmt": "Geräte-Manager", "tool.win.devmgmt.d": "Hardware und Treiber verwalten",
    "tool.win.control": "Systemsteuerung", "tool.win.control.d": "Klassische Systemeinstellungen",
    "tool.win.msinfo": "Systeminformationen", "tool.win.msinfo.d": "Systemkonfiguration ansehen",
    "tool.win.update": "Windows Update", "tool.win.update.d": "Nach Updates suchen",
    "tool.win.restore": "Systemwiederherstellung", "tool.win.restore.d": "Wiederherstellungspunkte erstellen/nutzen",
    "history.empty": "Noch keine Aktivitäten", "history.clear.title": "Verlauf leeren?", "history.clear.msg": "Alle Aufzeichnungen werden gelöscht.",
    "history.type.clean": "Bereinigung", "history.type.autoclean": "Auto", "history.type.restore": "Wiederherstellung",
    "history.type.uninstall": "Deinstallation", "history.type.startup": "Autostart", "history.type.quarantine": "Quarantäne",
    "history.type.shred": "Shredder", "history.type.other": "Sonstige",
    "settings.title": "Einstellungen", "settings.sec.general": "Allgemein", "settings.sec.exclude": "Ausschlüsse & Whitelist",
    "settings.sec.notify": "Benachrichtigungen", "settings.sec.advanced": "Erweitert", "settings.sec.privacy": "Datenschutz", "settings.sec.about": "Über",
    "settings.exc.desc": "Diese Ordner und Dateien werden bei allen Scans und Bereinigungen übersprungen.", "settings.exc.empty": "Keine Ausschlüsse oder Whitelist-Einträge",
    "settings.whitelist": "Whitelist", "settings.excluded": "Ausgeschlossen",
    "settings.btn.addexclude": "Ausgeschlossenen Ordner hinzufügen", "settings.btn.addwhitelist": "Datei/Ordner zur Whitelist",
    "settings.pick.whitelist": "Datei für die Whitelist wählen", "settings.pick.exclude": "Ordner wählen, der übersprungen wird",
    "settings.days": "Tage", "settings.threads": "Threads",
    "settings.theme.light": "Hell", "settings.theme.dark": "Dunkel", "settings.theme.system": "System folgen",
    "settings.freq.daily": "Täglich", "settings.freq.weekly": "Wöchentlich", "settings.freq.monthly": "Monatlich",
    "settings.lang.auto": "Systemsprache folgen",
    "settings.row.language": "Sprache", "settings.row.language.d": "Sofort wirksam",
    "settings.row.autostart": "Mit Windows starten", "settings.row.autostart.d": "Wartet nach dem Start still im Tray und tut nichts von selbst",
    "settings.row.mintotray": "In Tray minimieren", "settings.row.mintotray.d": "Die Minimieren-Schaltfläche versteckt im Tray",
    "settings.row.closetotray": "Schließen minimiert ins Tray", "settings.row.closetotray.d": "Die Schließen-Schaltfläche fragt und minimiert statt zu beenden",
    "settings.row.theme": "Design",
    "settings.row.quarantine": "In Quarantäne statt löschen", "settings.row.quarantine.d": "Nicht-Cache-Dateien landen zuerst in Quarantäne, wiederherstellbar (empfohlen)",
    "settings.row.quarantine.days": "Quarantäne-Aufbewahrung", "settings.row.quarantine.days.d": "Nach Ablauf automatisch endgültig gelöscht",
    "settings.row.autoclean": "Automatische Bereinigung", "settings.row.autoclean.d": "Bereinigt nach Plan sichere Elemente wie Tempdaten und Caches",
    "settings.row.autoclean.freq": "Häufigkeit", "settings.row.autoclean.freq.d": "Läuft im Hintergrund, solange die App offen ist",
    "settings.row.notifydisk": "Warnung bei wenig Speicher", "settings.row.notifydisk.d": "Warnt unter 10 % frei auf dem Systemlaufwerk (selten)",
    "settings.row.notifyauto": "Ergebnisse der Auto-Bereinigung", "settings.row.notifyweekly": "Wochenbericht",
    "settings.row.notifynews": "Produktneuigkeiten", "settings.row.notifynews.d": "Neue Funktionen und Aktionen, standardmäßig aus",
    "settings.row.threads": "Scan-Threads", "settings.row.threads.d": "Mehr Threads = schneller; bei HDDs niedriger einstellen",
    "settings.row.hidden": "Versteckte Dateien scannen", "settings.row.junction": "Verzeichnislinks folgen (Junctions)",
    "settings.row.junction.d": "Folgen von Links kann Daten doppelt zählen; standardmäßig aus",
    "settings.row.stats": "Anonyme Nutzungsstatistiken", "settings.row.stats.d": "Würde nur Nutzungszähler und Fehlercodes melden — dieser Build sendet nie etwas",
    "settings.row.crash": "Absturzberichte",
    "settings.privacy.desc": "Alle Scandaten bleiben auf diesem Gerät. Diese App sammelt oder sendet niemals Dateinamen, Pfade oder Inhalte.",
    "settings.about.slogan": "Klar bereinigen, sorgenfrei optimieren.", "settings.about.support": "Support & Feedback",
    "settings.about.site": "Webseite", "settings.about.email": "E-Mail", "settings.about.repo": "Quellcode",
    "settings.about.wechat": "Scanne oder suche „AI虚拟助理“ in WeChat für Tipps und Neuigkeiten.",
    "wizard.welcome": "Willkommen bei CleanMaster",
    "wizard.slogan": "Klar bereinigen, sorgenfrei optimieren.\nWir bieten nur erklärbare, voranschaubare, wiederherstellbare Bereinigung — keine Scheinoptimierung.",
    "wizard.privacy.title": "Unser Datenschutzversprechen",
    "wizard.privacy.items": "· Alle Scanergebnisse, Dateinamen und Pfade bleiben auf diesem PC.\n· Standardmäßig keine Telemetrie; Dateiinhalte werden nie hochgeladen.\n· Wichtige Bereinigungen landen in Quarantäne — 7~30 Tage wiederherstellbar.\n· Vor dem Löschen immer Vorschau — niemals heimlich gelöscht.",
    "wizard.auto.title": "Automatische Bereinigung aktivieren?", "wizard.auto.desc": "Bereinigt nur sichere Elemente wie Tempdaten und App-Caches, einmal pro Woche.",
    "wizard.auto.yes": "Aktivieren", "wizard.auto.no": "Jetzt nicht", "wizard.next": "Loslegen", "wizard.next2": "Weiter",
    "tray.open": "CleanMaster öffnen", "tray.quickscan": "Schnell-Scan", "tray.exit": "Beenden",
    "tray.autoclean": "Auto-Bereinigung: ", "tray.on": "ein", "tray.off": "aus",
    "dlg.exit.title": "CleanMaster beenden?", "dlg.exit.msg": "Beim Beenden stoppen automatische Bereinigung und Speicherüberwachung.",
    "toast.traymin": "Ins Tray minimiert — Rechtsklick auf das Tray-Symbol zum Beenden",
    "toast.scanstopped": "Scan gestoppt", "toast.scanfailed": "Scan fehlgeschlagen: ", "toast.noselect": "Erst Elemente zum Bereinigen auswählen",
    "toast.cleancancelled": "Bereinigung abgebrochen", "toast.cleanfailed": "Bereinigung fehlgeschlagen: ",
    "toast.nothing": "Nichts zu bereinigen gefunden", "toast.cleaned": "Bereinigt — {0} freigegeben",
    "toast.readfailed": "Laden fehlgeschlagen: ", "toast.langapplied": "Sprache geändert",
}
